.gitignore
experiments/package.json
experiments/src/getMetadata.ts
experiments/src/main.ts
package-lock.json
package.json

let's start with this and we can keep improving them... is that cool?

chore: experiments

---

package-lock.json
package.json
packages/substrate-client/src/chainhead/body.ts
packages/substrate-client/src/chainhead/call.ts
packages/substrate-client/src/chainhead/follow.ts
packages/substrate-client/src/chainhead/header.ts
packages/substrate-client/src/chainhead/operation-promise.ts
packages/substrate-client/src/chainhead/storage.ts
packages/substrate-client/src/chainhead/types.ts
packages/substrate-client/src/chainhead/unpin.ts
packages/substrate-client/src/client/createClient.ts
packages/substrate-client/src/transaction/transaction.ts
packages/substrate-client/src/utils/abortablePromiseFn.ts
packages/substrate-client/src/utils/subscriptions-manager.ts

How do I know that it works if we still don't have tests for this? Good question! B/c the experiments work on the latest version of smoldot 🙈 Please don't judge me! The tests are coming soon(ish)!

substrate-client: update client to latest spec

---

.github/workflows/ci.yml
.gitignore
experiments/package.json
package-lock.json
package.json
packages/substrate-bindings/dist/index.cjs
packages/substrate-bindings/dist/index.js
packages/substrate-bindings/package.json
packages/substrate-bindings/src/index.ts
packages/substrate-bindings/tsconfig-build.json
packages/substrate-client/dist/index.cjs
packages/substrate-client/dist/index.js
packages/substrate-client/package.json
packages/substrate-client/tsconfig-build.json
packages/substrate-codegen/dist/index.cjs
packages/substrate-codegen/dist/index.js
packages/substrate-codegen/package.json
packages/substrate-codegen/tsconfig-build.json

Closes #59 
Update build scripts to use [`tsup`](https://tsup.egoist.dev/).
`tsup` generates a single declaration file per bundle which helps to fix [Masquerading as CJS](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseCJS.md) and [Masquerading as ESM](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseESM.md).
The `package.json` has been updated as follows
```jsonc
{
// ...
"exports": {
".": {
"node": {
"production": {
// use minified version for CJS when NODE_ENV==production
"require": "./dist/min/index.js"
}
},
// "unofficial" field that is supported by bundlers like Webpack and Rollup
"module": "./dist/index.mjs",
// ESM entrypoint when using "import" statement or "import()" function
"import": …
```

feat: improve `esm`/`cjs` bundling and typings

---

packages/substrate-client/src/chainhead/chainhead.ts

Currently the logic of the `fRequest` function inside `chainHead` is a bit convoluted. The commit of this PR is an attempt to simplify it a bit.
FWIW: the tests definitely help me at making this small refactor with confidence 💪 😅.
EDIT: Also, I know that's not always a good indicator for having removed complexity, but this feels good 🙂 :

cleanup substrate-client `chainHead`

---

packages/substrate-client/src/chainhead/internal-types.ts
packages/substrate-client/src/chainhead/storage.ts

I missed to update [some of these events](https://github.com/paritytech/json-rpc-interface-spec/commit/1a145b257f107306dc376f7af3fc1eb7879ccf2d). We urgently need to add e2e tests, though.

fix: `chainHead` storage events

---

packages/cli/src/main.ts

example: https://gist.github.com/ryanleecode/59967d17c3bcf0e5e693ed18c1855446

cli(chore): export descriptors as tuple

---

packages/substrate-codegen/src/dynamic-builder.ts
packages/substrate-codegen/src/static-builder.ts

While working on the new client I came up with a few codegen improvements.

substrate-codegen: codegen improvements

---

experiments/package.json
pnpm-lock.yaml

chore: add cli to experiments

---

packages/cli/src/smolldot-worker.ts

cli: remove zod dependency in smolldot worker

---

packages/client/README.md
packages/client/package.json
packages/client/src/codecs.ts
packages/client/src/create-client.ts
packages/client/src/enhancers/limit-operations.ts
packages/client/src/enhancers/unpin.ts
packages/client/src/index.ts
packages/client/src/storage.ts
packages/client/src/types.ts
packages/client/src/utils.ts
packages/client/tsconfig.json
packages/substrate-codegen/src/dynamic-builder.ts
packages/substrate-codegen/src/static-builder.ts
pnpm-lock.yaml

A very raw/first pass of the "pull-client"

@polkadot-api/client first implementation

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitignore

primarily for being able to test zombienet locally

chore: add vscode dev container files

---

packages/tx-helper/src/get-tx-creator/get-tx-data.ts
packages/tx-helper/src/get-tx-creator/input.ts

It undoes the previous fix, and it makes a proper one.
PS: We need to find some time to work on these tests.

Fix: tx-helper overrides

---

packages/cli/package.json
packages/substrate-bindings/package.json
pnpm-lock.yaml

fix: scale-ts re-export

---

packages/cli/README.md

docs(cli): update readme

---

packages/cli/src/io/createDescriptorsFile.ts
packages/cli/src/io/createDtsFile.ts
packages/cli/src/io/getCodegenInfo.ts
packages/cli/src/io/io.ts
packages/substrate-codegen/src/static-builder.ts

A bunch of improvements into the codegen. With these changes TSC will have a lot less work, so that when the top-level client gets instantiated with a lot of descriptors the intellisense doesn't feel sluggish.

feat: improve static code generation

---

packages/sc-provider/package.json
pnpm-lock.yaml

Bootnodes changed so substrate connect needs to be updated.
https://github.com/paritytech/substrate-connect/pull/1575

chore(sc-provider): update substrate connect

---

experiments/package.json
package.json
packages/cli/package.json
packages/cli/src/main.ts
packages/client/src/codecs.ts
packages/light-client-extension-helpers/src/background/background-helper.ts
packages/rollup-plugin-descriptor-treeshake/package.json
packages/substrate-bindings/src/descriptors.ts
packages/substrate-client/src/chainhead/public-types.ts
pnpm-lock.yaml
vite/package.json

Upgrades `prettier` `tsup` and `typescript`

chore: dependency upgrades

---

examples/vite/src/main.ts
packages/client/src/tx.ts

Props to @peetzweg for pointing this out!! 🙏

feat(client): improve tx API

---

experiments/package.json
experiments/src/tx.ts
packages/sm-provider/src/sm-provider.ts
pnpm-lock.yaml

Improve the smoldot provider API and leverage it in one of the experiments.

chore(sm-provider): improve sm-provider API

---

packages/substrate-client/src/chainhead/chainhead.ts
packages/substrate-client/src/client/createClient.ts
packages/substrate-client/src/internal-utils/subscriptions-manager.ts

This is a temporary work-around (that we should remove in the coming weeks) to deal with the fact that most polkadot-sdk nodes are still affected by [this issue](https://github.com/paritytech/polkadot-sdk/issues/2992).

orphan subscriptions temporary work around

---

packages/node-polkadot-provider/src/node-provider.ts
packages/tx-helper/src/get-tx-creator/get-tx-data.ts
packages/tx-helper/src/get-tx-creator/input.ts
packages/tx-helper/src/types.ts

feat(tx-helper): improve `tx-helper` API

---

packages/cli/src/metadata.ts
packages/ws-provider/node/package.json
packages/ws-provider/package.json
packages/ws-provider/src/index.ts
packages/ws-provider/src/node.ts
packages/ws-provider/src/web.ts
packages/ws-provider/src/ws-provider.ts
packages/ws-provider/web/package.json
pnpm-lock.yaml

feat(ws-provider): subpaths for web and node

---

.github/workflows/ci.yml
.github/workflows/publish.yml
packages/json-rpc/logs-provider/README.md
packages/json-rpc/logs-provider/package.json
packages/json-rpc/logs-provider/src/index.ts
packages/json-rpc/logs-provider/src/logs-provider.ts
packages/json-rpc/logs-provider/src/queue.ts
packages/json-rpc/logs-provider/src/types.ts
packages/json-rpc/logs-provider/src/with-logs-recorder.ts
packages/json-rpc/logs-provider/tsconfig.json
pnpm-lock.yaml

This is going to make it a lot easier for us to both: capture the logs that happened when a bug occurred, and also to reproduce that exact same scenario.

feat(logs-provider): add `logs-provider` package

---

README.md
examples/react-teleport/src/api/relay-chain.ts
packages/client/README.md

docs: improve README

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/client/CHANGELOG.md
packages/client/package.json
packages/codegen/CHANGELOG.md
packages/codegen/package.json
packages/observable-client/CHANGELOG.md
packages/observable-client/package.json
packages/substrate-client/CHANGELOG.md
packages/substrate-client/package.json
packages/substrate-client/src/chainhead/body.ts
packages/substrate-client/src/chainhead/call.ts
packages/substrate-client/src/chainhead/chainhead.ts
packages/substrate-client/src/chainhead/operation-promise.ts
packages/substrate-client/src/client/createClient.ts
packages/substrate-client/src/request-compatibility-enhancer.ts

Fixes:
- codegen issue
- compatibility enhancers

polkadot-api@0.5.1

---

packages/codegen/src/known-types.ts

feat(known-types): remove duplicate names, cleanup generic enums

---

packages/client/CHANGELOG.md
packages/client/src/client.ts
packages/client/src/types.ts

feat(client): add `_request` API

---

integration-tests/zombie-tests/src/main.spec.ts
packages/client/CHANGELOG.md
packages/observable-client/CHANGELOG.md
packages/observable-client/src/chainHead/enhancers/operationLimitRecovery.ts

fix(observable-client): fix operation-limit-recovery issue

---

packages/observable-client/src/chainHead/enhancers/operationLimitRecovery.ts

I wasn't super happy with the fix that I did yesterday, so... 🙈 
The new code is 100% equivalent to the previous one, but a tiny bit less convoluted.

nit(observable-client): operationLimitRecovery nit

---

packages/client/CHANGELOG.md
packages/observable-client/CHANGELOG.md
packages/observable-client/src/chainHead/streams/get-runtime-creator.ts
packages/observable-client/src/chainHead/streams/pinned-blocks.ts
packages/observable-client/tests/fixtures.ts
packages/observable-client/tests/observableClient-stopError.spec.ts

fix: stop recovery when runtime hasn't loaded and finalized changes

---

packages/client/CHANGELOG.md
packages/signers/pjs-signer/CHANGELOG.md
packages/signers/pjs-signer/src/pjs-signed-extensions-mappers.ts
packages/signers/pjs-signer/src/types.ts

fix(pjs-signer): ensure payload to be the same as PJS api

---

packages/client/CHANGELOG.md
packages/client/src/tx/submit-fns.ts
packages/client/src/tx/types.ts

feat(client): add `blockNumber` to tx payload

---

packages/cli/CHANGELOG.md
packages/client/CHANGELOG.md
packages/codegen/CHANGELOG.md

I forgot updating the changelog on my previous PR #547

chore(codegen): add missing change to changelog

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/client/CHANGELOG.md
packages/client/package.json
packages/codegen/CHANGELOG.md
packages/codegen/package.json
packages/merkleize-metadata/CHANGELOG.md
packages/merkleize-metadata/package.json
packages/metadata-builders/CHANGELOG.md
packages/metadata-builders/package.json
packages/observable-client/CHANGELOG.md
packages/observable-client/package.json
packages/signers/pjs-signer/CHANGELOG.md
packages/signers/pjs-signer/package.json
packages/signers/polkadot-signer/CHANGELOG.md
packages/signers/polkadot-signer/package.json
packages/signers/signer/CHANGELOG.md
packages/signers/signer/package.json
packages/substrate-bindings/CHANGELOG.md
packages/substrate-bindings/package.json
packages/substrate-client/CHANGELOG.md
packages/substrate-client/package.json
packages/substrate-client/src/index.ts
packages/view-builder/CHANGELOG.md
packages/view-builder/package.json
pnpm-lock.yaml

Fix dependencies and release

---

packages/cli/CHANGELOG.md
packages/client/CHANGELOG.md
packages/codegen/CHANGELOG.md
packages/codegen/src/generate-descriptors.ts

fix: whitelist entry for pallet wildcards

---

packages/metadata-builders/tests/__snapshots__/dynamic-builder.spec.ts.snap
packages/substrate-bindings/src/codecs/scale/Binary.ts
packages/substrate-bindings/tests/codecs/Bynary.spec.ts

fix: values typed as `FixedSizeBinary` is only an instance of `Binary`

---

packages/client/CHANGELOG.md
packages/client/src/index.ts
packages/client/src/tx/index.ts
packages/client/src/tx/submit-fns.ts
packages/client/src/tx/tx.ts
packages/client/src/types.ts
packages/observable-client/CHANGELOG.md
packages/observable-client/src/chainHead/chainHead.ts
packages/observable-client/src/chainHead/track-tx.ts
packages/observable-client/src/chainHead/validate-tx.ts

After trying a lot of different options, I decided to settle for this one.
Closes #514

feat(client): `InvalidTxError`

---

packages/cli/src/commands/generate.ts

Fixes #597
Yarn 2 has a [portal](https://yarnpkg.com/protocol/portal) protocol, designed specifically for this usecase.

fix: `file:` protocol breaks yarn immutable installation

---

packages/client/CHANGELOG.md
packages/client/src/tx/submit-fns.ts

fix(client): handle unpinned block on analyzed block

---

packages/client/CHANGELOG.md
packages/client/chains/ksmcc3_encointer/package.json
packages/client/package.json
packages/client/src/reexports/chains_ksmcc3_encointer.ts
packages/known-chains/CHANGELOG.md
packages/known-chains/ksmcc3_encointer/package.json
packages/known-chains/package.json
packages/known-chains/specs/ksmcc3_encointer.json
packages/known-chains/src/index.ts

feat(chains): add encointer

---

packages/client/CHANGELOG.md
packages/known-chains/CHANGELOG.md
packages/known-chains/specs/paseo_asset_hub.json

Paseo AssetHub was restarted and therefore the `stateRootHash` changed. Updating bootnodes as well.

fix(chains): paseo chainspec assethub

---

examples/bun/src/test-unsorted-logs-bug.ts
packages/client/CHANGELOG.md
packages/json-rpc/polkadot-sdk-compat/CHANGELOG.md
packages/json-rpc/polkadot-sdk-compat/src/index.ts
packages/json-rpc/polkadot-sdk-compat/src/parsed-enhancers/fix-unordered-blocks.ts
packages/json-rpc/polkadot-sdk-compat/src/parsed-enhancers/index.ts

Fixes #671 .
Despite the fact that #671 is an upstream bug, it makes sense to create another enhancer in our end to mitigate the issue.

feat(polkadot-sdk-compat): unordered blocks enhancer

---

integration-tests/zombie-tests/src/main.spec.ts
packages/client/CHANGELOG.md
packages/client/src/client.ts
packages/client/src/tx/tx.ts
packages/client/src/tx/types.ts
packages/client/src/types.ts

This builds on top of #687. Should be merged after it.
Closes #527

feat(tx): add txFromCallData API

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/client/CHANGELOG.md
packages/client/package.json
packages/codegen/CHANGELOG.md
packages/codegen/package.json
packages/metadata-compatibility/CHANGELOG.md
packages/metadata-compatibility/package.json

**MERGE WITH SQUASH OR REBASE!**

Bring changelog to main from 1.2.1

---

packages/client/src/tx/tx.ts
packages/client/src/tx/types.ts

Closes #664 
I'm not sure that this is the best approach. I still want to discuss this with @voliva... But it's a start.

feat(client): add `tx.getPaymentInfo`

---

packages/client/CHANGELOG.md
packages/client/src/index.ts

feat(client): export compatibility token type

---

examples/ink/index.ts
examples/ink/psp22.json
packages/ink-contracts/src/dynamic-builders.ts
packages/ink-contracts/src/metadata-pjs-types.ts
packages/ink-contracts/src/metadata-types.ts

I forgot adding the codec for events on the ink dynamic-builder. Fear not, it's here now.

feat(ink): add codec for events

---

packages/docgen/CHANGELOG.md
packages/docgen/package.json
packages/docgen/src/generateDocs.ts
packages/docgen/src/main.ts
packages/docgen/tsconfig.json

**THIS PR RELEASES NEXT `@polkadot-api/docgen`**

feat(docgen): generate one single build for all chains

---

packages/client/CHANGELOG.md
packages/json-rpc/ws-provider/CHANGELOG.md
packages/json-rpc/ws-provider/package.json
packages/json-rpc/ws-provider/src/node.ts
packages/json-rpc/ws-provider/src/types.ts
packages/json-rpc/ws-provider/src/web.ts
packages/json-rpc/ws-provider/src/ws-provider.ts
packages/json-rpc/ws-provider/tsconfig.json
pnpm-lock.yaml

Closes https://github.com/polkadot-api/polkadot-api/issues/783

chore(ws-provider): fix types exports + minor improvements

---

.github/workflows/publish.yml
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/client/CHANGELOG.md
packages/client/package.json
packages/codegen/CHANGELOG.md
packages/codegen/package.json
packages/docgen/CHANGELOG.md
packages/docgen/package.json
packages/ink-contracts/CHANGELOG.md
packages/ink-contracts/package.json

polkadot-api@1.5.1

---

packages/client/CHANGELOG.md
packages/observable-client/CHANGELOG.md
packages/observable-client/src/chainHead/streams/get-runtime-creator.ts

Also, we should publish a hot-fix release quite promptly.

fix(observable-client): metadata v14 decoder

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/client/CHANGELOG.md
packages/client/package.json
packages/json-rpc/polkadot-sdk-compat/CHANGELOG.md
packages/json-rpc/polkadot-sdk-compat/package.json
packages/json-rpc/polkadot-sdk-compat/src/index.ts

polkadot-api@1.6.1

---

packages/cli/CHANGELOG.md
packages/cli/src/commands/generate.ts

fix(cli): unable to run codegen on windows

---

packages/client/CHANGELOG.md
packages/known-chains/CHANGELOG.md
packages/known-chains/specs/paseo.json
packages/known-chains/specs/paseo_asset_hub.json

fix(chainspecs): Paseo ss58Format value

---

packages/client/CHANGELOG.md
packages/observable-client/CHANGELOG.md
packages/observable-client/src/chainHead/storage-queries.ts

A pragmatical workaround [this PolkadotSDK issue](https://github.com/paritytech/polkadot-sdk/issues/6683)

fix(observable-client): storage-queries fix

---

packages/signers/meta-signers/CHANGELOG.md
packages/signers/meta-signers/package.json
packages/signers/meta-signers/src/index.ts

fix(meta-signers): missing export getProxySigner

---

integration-tests/chopsticks/src/chopsticks.ts
integration-tests/chopsticks/src/providerInterceptor.ts
integration-tests/chopsticks/src/stop-events.spec.ts
packages/cli/CHANGELOG.md
packages/client/CHANGELOG.md
packages/observable-client/CHANGELOG.md
packages/observable-client/src/chainHead/streams/follow.ts

Closes #966
Second attempt, but this time I could reproduce the issue in papi-console, and created a test with it.

fix: missing chainHead subscription

---

packages/cli/CHANGELOG.md
packages/client/CHANGELOG.md
packages/codegen/CHANGELOG.md
packages/codegen/src/generate-descriptors.ts
packages/codegen/src/generate-docs-descriptors.ts
packages/codegen/src/internal-types/generate-typescript.ts

fix(codegen): entry docs not getting stripped properly

---

integration-tests/chopsticks/src/events.spec.ts
packages/client/CHANGELOG.md
packages/observable-client/CHANGELOG.md
packages/observable-client/src/utils/concatMapEager.ts

fix(event): `event.watch()` completing the observable on specific scenarios.

---

packages/observable-client/src/chainHead/chainHead.ts
packages/observable-client/src/chainHead/enhancers/index.ts
packages/observable-client/src/chainHead/enhancers/optionalHash.ts

fix(observable-client): fix error in camel case spelling of `getWithOptionalHash`

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/client/CHANGELOG.md
packages/client/package.json
packages/docgen/CHANGELOG.md
packages/docgen/package.json
packages/raw-client/CHANGELOG.md
packages/raw-client/package.json
packages/substrate-client/CHANGELOG.md
packages/substrate-client/package.json

polkadot-api@1.15.4

---

packages/client/CHANGELOG.md
packages/client/src/client.ts
packages/client/src/types.ts

I'm still a bit on the fence about the name, though 😅.

feat(client): add `hodlBlock` API

---

integration-tests/zombie-tests/src/main.spec.ts

This should approximately halve the time zombienet tests take. Approximately, it reduces from 5min to 2min the execution time.
Changes:
- Increase concurrency inside zombienet tests.
- Merge `custom nonce` and `custom mortality` tests.
- Remove `consecutive transactions` test, testing the same as `optimistic transactions` test.

test(zombienet): increase concurrency

---

integration-tests/zombie-tests/src/main.spec.ts
packages/client/CHANGELOG.md
packages/smoldot/CHANGELOG.md
packages/smoldot/package.json
pnpm-lock.yaml

fix(smoldot): update to 2.0.38
