polkadot-api/polkadot-api

packages/substrate-codegen/src/build-syntax.ts
When I got rid of `lazy` in favour of `Self` I propagated the change to `build-codec`, but I forgot to update `build-syntax` accordingly. This PR amends that.
=> codegen: `lazy` -> `Self` on `build-syntax`

package-lock.json, package.json, packages/substrate-bindings/tsconfig-build.json, packages/substrate-bindings/tsconfig.json, packages/substrate-client/tsconfig-build.json, packages/substrate-client/tsconfig.json, packages/substrate-codecs/tests/AccountId.spec.ts, packages/substrate-codecs/tsconfig-build.json, packages/substrate-codecs/tsconfig.json, packages/substrate-codegen/tsconfig-build.json, packages/substrate-codegen/tsconfig.json, tsconfig.base.json, vitest.config.ts
Share a common `tsconfig.json` across workspace packages.
Note: all relative paths found in the base configuration file will be resolved relative to the configuration file they originated in (see [extends](https://www.typescriptlang.org/tsconfig#extends)).
For example
- `include`/`exclude`
- `compilerOptions`
- `baseUrl`
- `paths`
=> chore: add base tsconfig

packages/substrate-bindings/tests/hashes/blake2.spec.ts, packages/substrate-bindings/tests/hashes/h64.spec.ts, packages/substrate-bindings/tests/hashes/identity.spec.ts, packages/substrate-bindings/tests/hashes/twoX.spec.ts, packages/substrate-bindings/tests/storage.spec.ts
The `substrate-codecs` package has the tests inside the tests folder, while the `substrate-bindings` package has the tests besides the files that are being tested. This PR just makes things consistent. I don't have very strong opinions about which approach is best, but I'm starting to like this approach better than the other one...
=> chore: move tests to `tests` folder

packages/substrate-bindings/src/descriptors.ts, packages/substrate-bindings/src/index.ts
I've been going on and on about "descriptors" and how they're the magic behind the "capi-client". I get the feeling I might've confused you a bit. My bad.
So, here's the deal. I'm opening this PR with the basic types of these descriptors. I've thrown in some type-helpers too, so you can see their potential for creating some cool APIs.
While I'm pretty sure about the core descriptor types (`StorageDescriptor`, `EventDescriptor`, `CallDescriptor`, and `ConstantDescriptor`), a lot of stuff in this PR is still being ironed out. Plus, we need more type-helpers.
Why this PR? Two reasons:
1. I wanted to show you what these descriptor types look like, clear up any confusion.
2. I'm dropping another PR soon about the `codegen` updates for these "descriptors", so it'd be cool if you got a hang of …
=> substrate-bindings: unpolished `descriptors`

packages/substrate-client/src/chainhead/chainhead.ts, packages/substrate-client/tests/chainHead.spec.ts
This issue on the JSON-RPC spec repo, made me realize that the `stop` event should immediately reject all ongoing operations and/or requests on the `chainHead` subscription. The current tests are testing that things get rejected right after getting the expected response from the server, but that's wrong and unnecessary. So this PR has 2 commints:
1. It alters the existing test to make sure that we don't wait for the responses once the `stop` event has occurred.
2. It fixes the code to make sure that the test passes.
=> substrate-client: fix stop issue

packages/substrate-bindings/src/descriptors.ts
During runtime we need to know the arity of the function that we are dealing with. This is most important when it comes to building the different possible storage calls. So, yeah, I missed that.
=> substrate-bindings(feat): improve descriptors

packages/cli/package.json, pnpm-lock.yaml
Need to add it back since its being used in smolldot worker
https://github.com/paritytech/polkadot-api/blob/main/packages/cli/src/smolldot-worker.ts#L3
=> fix: add back sc-provider to cli

experiments/src/all-nominators.ts, experiments/src/getMetadata.ts, packages/client/src/create-client.ts, packages/substrate-client/src/chainhead/chainhead.ts, packages/substrate-client/src/chainhead/internal-types.ts, packages/substrate-client/src/chainhead/operation-promise.ts, packages/substrate-client/src/chainhead/public-types.ts, packages/substrate-client/src/chainhead/storage.ts, packages/substrate-client/src/transaction/transaction.ts, packages/substrate-client/src/transaction/types.ts, packages/substrate-client/tests/chainHead-operations.spec.ts, packages/substrate-client/tests/chainHead.spec.ts, packages/substrate-client/tests/storage.spec.ts, packages/substrate-client/tests/transaction.spec.ts
This PR amends a wrong that's been driving me nuts for a while: when I created the `substrate-client`, I mistakenly named the property used for the discriminated unions `event`, rather than naming it `type`. As a result we had lots of code that looked like this `if (event.event === "started")`, etc, etc.
I rather addressing this issue before it's too late.
=> substrate-client: `event` to `type`

experiments/package.json, experiments/src/tx.ts, packages/tx-helper/README.md, packages/tx-helper/package.json, packages/tx-helper/src/get-tx-creator/get-relevant-signed-extensions.ts, packages/tx-helper/src/get-tx-creator/get-tx-creator.ts, packages/tx-helper/src/get-tx-creator/get-tx-data.ts, packages/tx-helper/src/get-tx-creator/index.ts, packages/tx-helper/src/get-tx-creator/input.ts, packages/tx-helper/src/get-tx-creator/multi-address-encoder.ts, packages/tx-helper/src/get-tx-creator/signature-encoder.ts, packages/tx-helper/src/get-tx-creator/version-bytes.ts, packages/tx-helper/src/index.ts, packages/tx-helper/src/internal-types.ts, packages/tx-helper/src/signed-extensions/chain/CheckGenesis.ts, packages/tx-helper/src/signed-extensions/chain/CheckNonce.ts, packages/tx-helper/src/signed-extensions/chain/CheckSpecVersion.ts, packages/tx-helper/src/signed-extensions/chain/CheckTxVersion.ts, packages/tx-helper/src/signed-extensions/chain/index.ts, packages/tx-helper/src/signed-extensions/index.ts, packages/tx-helper/src/signed-extensions/user/ChargeAssetTxPayment.ts, packages/tx-helper/src/signed-extensions/user/ChargeTransactionPayment.ts, packages/tx-helper/src/signed-extensions/user/CheckMortality.ts, packages/tx-helper/src/signed-extensions/user/index.ts, packages/tx-helper/src/signed-extensions/utils.ts, packages/tx-helper/src/types.ts, packages/tx-helper/tsconfig.json, pnpm-lock.yaml
This PR adds the first working version of the `@polkadot-api/tx-helper` that I already describe in [this blog-post](https://forum.polkadot.network/t/polkadot-provider-api-a-common-interface-for-building-decentralized-applications/4128#polkadot-apitx-helper-12).
Internally this library leverages a bunch of `@polkadot-api/*` libraries. However, it's worth noting that those are internal implementation details that don't leak through its public API.
Please have a look at the new experiment (`tx`) that I've added to demonstrate how the library can be used. I've performed all sorts of tests using that experiment to make sure that things work correctly.
Next steps:
- Integration tests (probably using zombienet)
- Performance optimizations: There are a bunch of requests that could be avoided, …
=> @polkadot-api/tx-helper

packages/cli/src/io.ts, packages/cli/test/cli.spec.ts
- fixes missing `len` in extrinsic descriptors
- fixes storage descriptors not compiling due to tsc failing to infer the type of the descriptor. 
- improves integration test --> for each descriptor in descriptor.json we check by using dynamic import to see if it was generated in codegen.
=> fix(cli): descriptor codegen

packages/cli/src/main.ts
Adds inputs validation for the descriptor json file name such that it cannot be equal to the codegen output directory.
=> chore(cli): add input validation

.github/workflows/ci.yml, experiments/src/all-nominators.ts, experiments/src/getMetadata.ts, experiments/src/smolldot-worker.ts, packages/cli/src/metadata.ts, packages/cli/src/smolldot-worker.ts, packages/json-rpc-provider-proxy/README.md, packages/json-rpc-provider-proxy/package.json, packages/json-rpc-provider-proxy/src/get-sync-provider.ts, packages/json-rpc-provider-proxy/src/index.ts, packages/json-rpc-provider-proxy/src/internal-types.ts, packages/json-rpc-provider-proxy/src/subscription-manager/chainHeadFollow.ts, packages/json-rpc-provider-proxy/src/subscription-manager/index.ts, packages/json-rpc-provider-proxy/src/subscription-manager/subscription-manager.ts, packages/json-rpc-provider-proxy/src/subscription-manager/transaction-submit-watch.ts, packages/json-rpc-provider-proxy/tsconfig.json, packages/json-rpc-provider/src/index.ts, packages/sc-provider/package.json, packages/sc-provider/src/index.ts, packages/substrate-client/src/client/createClient.ts, packages/substrate-client/src/index.ts, packages/substrate-client/tests/fixtures.ts, packages/tx-helper/src/types.ts, pnpm-lock.yaml
This PR is a follow-up to [this discussion](https://forum.polkadot.network/t/polkadot-provider-api-a-common-interface-for-building-decentralized-applications/4128/9?u=josep) I had with @tomaka.
**Main Changes**:
- Leveraging the capabilities of the new JSON-RPC API, the transportation layer's status is now hidden within the `json-rpc-provider`. This has allowed us to simplify the interfaces within `@polkadot-api/json-rpc-provider` as shown below:
```ts
export interface Provider {
send: (message: string) => void;
disconnect: () => void;
}
export declare type ConnectProvider = (
onMessage: (message: string) => void,
) => Provider;
```
- Introduced a new package, `@polkadot-api/json-rpc-provider-proxy`, to manage the transportation layer's status across different implementations. The main …
=> Better `json-rpc-provider`

packages/tx-helper/src/get-tx-creator/get-tx-creator.ts, packages/tx-helper/src/get-tx-creator/get-tx-data.ts, packages/tx-helper/src/internal-types.ts, packages/tx-helper/src/signed-extensions/chain/CheckGenesis.ts, packages/tx-helper/src/signed-extensions/chain/CheckNonce.ts, packages/tx-helper/src/signed-extensions/chain/CheckSpecVersion.ts, packages/tx-helper/src/signed-extensions/chain/CheckTxVersion.ts, packages/tx-helper/src/signed-extensions/user/ChargeAssetTxPayment.ts, packages/tx-helper/src/signed-extensions/user/ChargeTransactionPayment.ts, packages/tx-helper/src/signed-extensions/user/CheckMortality.ts, packages/tx-helper/src/types.ts
- The resulting `createTx` function now takes an optional argument which allows the consumer to provide a specific callback function, which will be used for that particular call.
- Cleaning up the code a bit and making variable names more consistent with the field-names that appear on the metadata.
=> tx-helper improvements

packages/substrate-bindings/src/descriptors.ts
Changes the generic to use array instead of tuple because if we use tuple we always need to have 1 element. If we must have 1 element, it prevents a "fire and forget" usage of the tx where the user doesn't care about the events or errors.
=> fix: txdescriptor event and error generics

packages/cli/src/main.ts
Fixes an issue where certain pallets couldn't be selected because the `idx` to `getLookupFn` was `NaN`
=> fix(cli): get look up entries

.github/workflows/ci.yml
Fixes https://github.com/paritytech/npm_publish_automation/actions/runs/6812714969/job/18525679043#step:6:24
`npm_publish_automation` expects a single artifact
https://github.com/paritytech/npm_publish_automation/blob/3fc4f3af68fe9974abd4250a9575f37291de9009/publishPackages.ts#L26-L28
=> fix: publish by uploading exactly 1 artifact

packages/cli/src/main.ts
Fixes missing input validation for input prompts and add a default for codegen output directory.
=> fix(cli): add input validation for input prompts

packages/light-client-extension-helpers/src/background/background-helper.ts, packages/light-client-extension-helpers/src/background/smoldot-provider.ts, packages/light-client-extension-helpers/src/background/types.ts, packages/light-client-extension-helpers/src/extension-page/extension-page-helper.ts, packages/light-client-extension-helpers/src/protocol.ts
Replace `genesisHash: string` with `chain: PageChain` in the return type from  `LightClientPageHelper.getActiveConnections()`
=> feat: add `chain` to `LightClientPageHelper.getActiveConnections()` response

packages/rollup-plugin-descriptor-treeshake/package.json, packages/rollup-plugin-descriptor-treeshake/rollup.config.js, packages/rollup-plugin-descriptor-treeshake/src/astSymbolTracker.spec.ts, packages/rollup-plugin-descriptor-treeshake/src/astSymbolTracker.ts, packages/rollup-plugin-descriptor-treeshake/src/index.ts, packages/rollup-plugin-descriptor-treeshake/src/whitelist.ts, packages/rollup-plugin-descriptor-treeshake/tsconfig.json, pnpm-lock.yaml, vite/package.json, vite/vite.config.ts
My attempt at solving #198 through method [2a].
I've built a rollup plugin (which is compatible with vite) that given the path to a codegen folder, detects calls to `createClient` using the generated descriptors, traces their usages and removes the unused descriptors from the build.
With the current example of `vite/src/main.ts`, the minified code is shaved by ~50kB:
```
minified
dist/assets/index-9b9328ce.js                       140.46 kB │ gzip:    53.27 kB
dist/assets/index-91969805.js                        89.86 kB │ gzip:    31.66 kB
```
Resulting built code without the plugin:
Resulting built code with the plugin:
This plugin is able to trace many common cases:
```ts
import { createClient } from "@polkadot-api/client";
import testDescriptors from "./codegen/test";
function …
```
=> feat(cli): remove unused symbols from codegen

packages/substrate-codegen/src/static-builder.ts
Fixes an issue where the static builder was overwriting existing declarations.
=> fix(substrate-codegen): static builder overwriting existing declarations

experiments/package.json, experiments/src/client.ts
=> chore: improve `client` experiment

experiments/src/getMetadata.ts
Experiments ts `getMetadata` was throwing error:
```
file:///home/wirednkod/Documents/repos/parity/ts/polkadot-api/experiments/dist/main.js:3
ScProvider,
^^^^^^^^^^
SyntaxError: The requested module '@polkadot-api/sc-provider' does not provide an export named 'ScProvider'
at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
at async loadESM (node:internal/process/esm_loader:34:7)
at async handleMainPromise (node:internal/modules/run_main:106:12)
```
=> Fix getMetadata in experiments

experiments/package.json, experiments/src/best-blocks.ts, packages/client/src/client.ts, packages/client/src/observableClient/chainHead/chainHead.ts, packages/client/src/observableClient/chainHead/index.ts, packages/client/src/observableClient/chainHead/streams/best-block.ts, packages/client/src/observableClient/index.ts, packages/substrate-bindings/src/codecs/blockHeader.ts
closes #218 
It adds 2 new APIs:
1) An API that simply observes the current best block hash
2) A more useful API which observes the current list of best-block headers. The list changes any time that either the current finalized and/or the current best block changes. Basically, it observes the "gap" of blocks from the currently finalized block to the best-block.
A new experiment has been added in order to easily test this new APIs.
=> feat(client): best-blocks

.github/workflows/ci.yml, .github/workflows/zombienet.yml, .gitignore, examples/decode-viewer/turbo.json, package.json, packages/cli/turbo.json, packages/rollup-plugin-descriptor-treeshake/turbo.json, pnpm-lock.yaml, turbo.json, vite/turbo.json
Add [turbo](https://turbo.build/) incremental build system
For example, the `build` step in the `pack` job uses `turbo` cache for the `build` script and it takes 1s
=> feat: use turbo repo

examples/vite/src/main.ts, packages/client/src/client.ts, packages/client/src/tx.ts, packages/client/src/types.ts, packages/metadata-builders/src/dynamic-builder.ts, packages/metadata-builders/src/static-builder.ts, packages/metadata-builders/tests/__snapshots__/dynamic-builder.spec.ts.snap, packages/substrate-bindings/src/descriptors.ts
Today I demoed to @peetzweg the latest improvements introduced by #256. During that call we noticed this improvement in the tx API, which makes it trivial to re-use the tx created with the client as inputs into the list of batched calls of the `Utility.batch` et al.
=> feat: better tx API

packages/substrate-client/src/chainhead/public-types.ts, packages/substrate-client/tests/chainHead-functions.spec.ts, packages/substrate-client/tests/chainHead-operations.spec.ts, packages/substrate-client/tests/chainHead.spec.ts, packages/substrate-client/tests/fixtures.ts, packages/substrate-client/tests/transaction.spec.ts
This is a small refactor for substrate-client integration test mocks. Essentially it has the same as before but reorganised in a way that I think that it's easier to think about.
My idea is to have a `MockProvider extends ConnectProvider` that has the functions to send messages and assert the received ones.
Then you can build on top of that to create other mock functions that provide more utilities: one for chainHead, another for transaction, etc.
I also liked the `getNewMessages()` function to exclude past calls, so I brought those to spies (onMsg, onError)
=> chore(substrate-client): flatten out fixtures on tests

packages/substrate-client/tests/chainHead-functions.spec.ts, packages/substrate-client/tests/chainHead-operations.spec.ts, packages/substrate-client/tests/chainHead.spec.ts, packages/substrate-client/tests/createClient.spec.ts, packages/substrate-client/tests/fixtures.ts
I have added a couple of tests: One that checks that an error on an operation doesn't kill the subscription, and another that just covers when the connection is created and destroyed. 
And the test "stops receiving messages upon cancelation"  wasn't covering the case correctly, as it was sending a message that couldn't be mapped to an operationId (and the assertion passed because it was checking that no messages were received).
The other changes are mainly types, style, etc.
=> test(substrate-client): improve tests on substrate-client

packages/metadata-builders/src/checksum-builder.ts, packages/metadata-builders/src/dynamic-builder.ts, packages/metadata-builders/src/lookups.ts, packages/metadata-builders/src/static-builder.ts, packages/metadata-builders/src/view-builder/view-builder.ts, packages/metadata-builders/tests/__snapshots__/checksum-builder.spec.ts.snap, packages/metadata-builders/tests/__snapshots__/view-builder.spec.ts.snap
Prior to these changes any `[u8; 32]` was being typed and encoded/decoded as a `SS58String` 🙈 That worked well most of the times, however there were many other cases for which this was completely wrong and undesirable, for instance the `parent_hash` field of a header was being encoded/decoded and typed as a `SS58String` 😬.
This PR fixes that issue.
=> chore: improve `AccountId32` types

packages/substrate-client/src/chainhead/chainhead.ts, packages/substrate-client/src/client/DestroyedError.ts, packages/substrate-client/src/client/createClient.ts, packages/substrate-client/src/client/index.ts, packages/substrate-client/src/index.ts, packages/substrate-client/src/transaction/transaction.ts, packages/substrate-client/tests/chainHead-functions.spec.ts, packages/substrate-client/tests/chainHead-operations.spec.ts, packages/substrate-client/tests/chainHead.spec.ts, packages/substrate-client/tests/fixtures.ts, packages/substrate-client/tests/transaction.spec.ts
While working on improving tests I found this gap: It's theoretically possible to call `client.destroy()`, which disconnects from the provider, and the ongoing promises are left unresolved.
I propose that they should be rejected with a DisjointError (as if the subscription was stopped), and I have added a possible fix.
We'll have to check for the same case on transaction.
=> fix(substrate-client): reject ongoing chainHead promises with DisjointError after calling disconnect

packages/client/package.json, packages/client/src/observableClient/chainHead/streams/pinned-blocks.ts, packages/client/tests/fixtures.ts, packages/client/tests/mockSubstrateClient.ts, packages/client/tests/observableClient.spec.ts, packages/client/tests/observe.ts
I found that blocks were not getting unpinned after they were pruned on a finalize event, from the [JSON-RPC Spec on pinning](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_follow.html#pinning):
> Blocks stay pinned even if they have been pruned from the chain of blocks, and must always be unpinned by the JSON-RPC client.
=> test(client): add tests to observableClient

packages/cli/src/metadata.ts
Currently the `@polkadot-api/ws-provider` assumes that the `WebSocket` interface is present in the global-scope, which is not the case on non-browser environments. Therefore, when we added the `ws-provider` we accidentally broke the `cli` when using the `wsURL` flag. So, this is a quick "fix" to address that issue.
Probably a better fix would be to have the `ws-provider` return a higher-order-function that first receives the `WebSocket` interface and then it returns the actual get-provider function. However, I want to think a bit more about that before making that change.
=> fix(cli): add `WebSocket` into global scope

packages/substrate-bindings/src/codecs/scale/Variant.ts
Function arguments were being wrongly inferred.
=> fix(substrate-bindings): fix type `Anonymize`

packages/client/src/observableClient/chainHead/chainHead.ts, packages/client/src/observableClient/chainHead/track-tx.ts, packages/client/src/tx.ts
One of the challenging things about #247 is the fact that it will be on us to track down the transaction in a performant manner. This PR adds that functionality.
Basically, what this PR does is to use the "old" [`transactionWatch_unstable_submitAndWatch`](https://paritytech.github.io/json-rpc-interface-spec/api/transactionWatch_unstable_submitAndWatch.html#transactionwatch_unstable_submitandwatch) method, but then it stops the operation as soon as it has emitted the "broadcasted" event, at which point it starts tracking down the transaction. This is a temporary workaround while we wait for smoldot to implement the new "transaction broadcast" API.
=> feat(client): track tx

packages/client/src/observableClient/chainHead/chainHead.ts
If when the consumer calls `chainhead.unfollow()`, like the [zombienet tests currently do](https://github.com/polkadot-api/polkadot-api/blob/9a68a6a6512cdb6d0cac0a5c178a09b036bb58d3/zombie-tests/src/0001-check-tx.ts#L251) while there is an `unpin` request on the fly, then that request will be rejected with a `DisjointError`, which is obviously not a big deal.
The problem, though, is precisely that we are treating `unpin` requests like fire-and-forget requests, so that triggers an unhandled rejection which makes the tests not pass when that occurs. This change avoids the issue. It's totally fine to ignore `DisjointError`s on `unpin` requests, because if it's disjoined, meaning that the block is certainly no longer pinned.
=> fix(ci): zombienet flaky test

packages/cli/src/io/createDescriptorsFile.ts, packages/cli/src/io/getCodegenInfo.ts, packages/cli/src/io/io.ts, packages/client/src/client.ts, packages/client/src/observableClient/chainHead/streams/get-runtime-creator.ts, packages/client/src/tx.ts, packages/client/src/types.ts, packages/legacy-polkadot-provider/src/get-tx-creator/get-tx-creator.ts, packages/legacy-polkadot-provider/src/get-tx-creator/get-tx-data.ts, packages/legacy-polkadot-provider/src/get-tx-creator/signed-extensions/user/ChargeAssetTxPayment.ts, packages/legacy-polkadot-provider/src/legacy-provider.ts, packages/legacy-polkadot-provider/src/types/internal-types.ts, packages/legacy-polkadot-provider/src/types/public-types.ts, packages/node-polkadot-provider/src/node-provider.ts, packages/node-polkadot-provider/src/types/json-rpc-provider.ts, packages/node-polkadot-provider/src/types/public-types.ts, packages/substrate-bindings/src/descriptors.ts, packages/tx-helper/src/get-tx-creator/get-tx-creator.ts, packages/tx-helper/src/get-tx-creator/get-tx-data.ts, packages/tx-helper/src/signed-extensions/user/ChargeAssetTxPayment.ts, packages/tx-helper/src/types.ts
These changes allow dApp developers to "hint" some values for the sign-extensions that require from user input while creating a TX.
The trickiest part was the `asset` hint, which will only be available for chains that support the `ChargeAssetTxPayment` signed extension, but in the end I think that it's working quite nicely.
=> feat: hinted "signed extensions"

packages/client/src/observableClient/chainHead/streams/pinned-blocks.ts, packages/client/tests/fixtures.ts, packages/client/tests/observableClient.spec.ts, packages/substrate-client/src/chainhead/chainhead.ts, packages/substrate-client/src/chainhead/json-rpc-types.ts, packages/substrate-client/src/chainhead/public-types.ts, packages/substrate-client/tests/chainHead.spec.ts, zombie-tests/src/0001-checkStorage.ts
Getting things ready for [this change](https://github.com/paritytech/json-rpc-interface-spec/pull/136) on the JSON-RPC spec
=> feat: `finalizedBlockHashes`

packages/client/src/observableClient/chainHead/track-tx.ts
Not the ideal fix, but for now it will do.
=> fix(client): `track-tx` quick fix

packages/client/src/observableClient/chainHead/chainHead.ts, packages/client/src/observableClient/chainHead/streams/pinned-blocks.ts, packages/client/src/observableClient/index.ts, packages/client/tests/observableClient.spec.ts, packages/substrate-client/src/chainhead/unpin.ts
The unpinning logic was a bit too convoluted, mainly because of the "cleaner" which happened on a time interval... Therefore, making it more challenging to get deterministic behaviours based on logs.
These changes make the unpinning logic a lot more straightforward, at the same time that they ensure that blocks get unpinned in the very same moment when the "unpinning condition" is met (the time interval has been removed). There is also a new well-known-error named `BlockNotPinned` which will get triggered if the consumer tries to perform an operation against a non-pinned block.
=> feat(client): improve unpinning logic

package.json, packages/client/package.json, packages/client/tests/mockSubstrateClient.ts, packages/legacy-polkadot-provider/package.json, packages/node-polkadot-provider/package.json, packages/rollup-plugin-descriptor-treeshake/package.json, packages/substrate-client/package.json, packages/tx-helper/package.json, pnpm-lock.yaml, tsconfig.base.json
Things to note:
* I added "run" parameter into the top-level package.json's test so when we run `pnpm test` it runs all test in non-watch mode
* top-level package has `"type": "module"` reason https://github.com/vitejs/vite/issues/15010.
* tsconfig.base.json has `"moduleResoultion": "Bundler"` reason https://github.com/vitest-dev/vitest/issues/4567
=> chore: update vitest to v1

packages/cli/src/commands/generate.ts, packages/client/src/client.ts, packages/client/src/constants.ts, packages/client/src/event.ts, packages/client/src/re-exports.ts, packages/client/src/tx.ts, packages/codegen/src/generate-descriptors.ts, packages/codegen/src/generate-multiple-descriptors.ts, packages/codegen/src/get-used-checksums.ts, packages/codegen/src/index.ts, packages/metadata-builders/src/checksum-builder.ts, packages/substrate-bindings/src/types/descriptors.ts
This is the first PR of a rework on the codegen, with the ultimate goal of reducing the initial bundle size.
This PR separates the combined checksum values from multiple chains into a separate file, and makes the descriptor file just reference the index.
Also solves conflicts of different types having the same name across multiple chains, which will be useful for the next change which will bring all the type/enums out from the descriptor file.
=> feat(cli): reuse checksums across multiple chains

packages/cli/src/commands/generate.ts, packages/codegen/src/generate-descriptors.ts, packages/codegen/src/generate-multiple-descriptors.ts, packages/codegen/src/generate-types.ts, packages/codegen/src/get-new-types.ts, packages/codegen/src/types-builder.ts, packages/metadata-builders/src/checksum-builder.ts
Next PR of the ongoing rework to the codegen.
This PR moves all the type definitions and enums out from the descriptor file into a separate file, which will be common for all chains (each chain will have one descriptor file, that imports types from the common type file, similar to #339)
WIP.... I changed a couple of things I want to check I'm not exposing any private name outside (`I{checksum}` types)
=> refactor(types-builder): merge types from multiple chains into one file (WIP)

examples/vite/src/main.ts, integration-tests/zombie-tests/src/main.spec.ts, packages/client/src/client.ts, packages/client/src/tx.ts, packages/client/src/types.ts
This PR introduces a number of changes in order to improve the public API for creating transactions:
- The `client` now exposes 2 new methods (`submit` and `submitAndWatch`) which take a signed transaction as an input and then validate, broadcast and report whether the transaction was included in a finalized block.
- The typed-api transaction methods were very poorly named, so they have been renamed as follows:
- `getTx` -> `sign`
- `submit` -> `signAndSubmit`
- `submit$` -> `signSubmitAndWatch`
- `callData` -> `decodedCall`
- Additionally, the Observable returned from the `signSubmitAndWatch` function now emits an initial event of type `signed` which reports the "raw" transaction.
It closes #346 (I will elaborate on that in the issue, though)
=> feat(client): improve tx API

packages/substrate-client/src/chainhead/storage.ts
Fixes #355 
I'm struggling to come up with a good test for this... Ideally, I would like to test it through an integration test.
=> fix(substrate-client): `Maximum call stack size exceeded`

examples/commonjs/package.json, examples/commonjs/src/index.js, examples/vite/package.json, examples/vite/src/main.ts, experiments/package.json, experiments/src/all-nominators.ts, experiments/src/best-blocks.ts, experiments/src/client.ts, experiments/src/getMetadata.ts, experiments/src/headers.ts, experiments/src/smolldot-worker.ts, packages/json-rpc/sc-provider/package.json, packages/json-rpc/sc-provider/src/index.ts, pnpm-lock.yaml
The reason why this is necessary is because of bundle-sizes. The thing is that `@substrate/connnect` performs various dynamic imports in order to generate smaller bundle-sizes (which automatically triggers bundlers to generate different dynamic chunks). However, in order to leverage this optimization `@substrate/connect` can't be a transient dependency, it must be installed directly as a dependency of the project that it's being bundled. Otherwise, all the different bundlers (vite, parcel, webpack, etc) will just create a humongous chunk with all the `@substrate/connect` assets.
=> Separate `@substrate/connect` from sc-provider

experiments/src/migrate-known-types.ts, integration-tests/zombie-tests/src/main.spec.ts, packages/json-rpc/sm-provider/src/sm-provider.ts
With this improvement on the public API of the `@polkadot-api/sm-provider` the `getSmProvider` function expects just the `smoldot` `Chain` as its input. It can be either a `Promise<Chain>` or a `Chain`.
This is possible thanks to the fact that in order to listen to the messages of the chain, the consumer doesn't have to register the callback function when setting it up. Instead the chain exposes a `nextJsonRpcResponse` function which returns a Promise that should resolve when there is a new message.
Thanks to this change, it will now be simpler to create para-chain connections, as the consumer won't have to create a redundant relay-chain.
=> feat(sm-provider): improve public API

NEWS.md, README.md
Better late than never... I totally forgot about the fact that I was supposed to state this. I mean, I already stated it in the Polkassembly discussion, but I'm pretty sure that Parity expected me to state this in the repo, which makes a lot of sense.
=> transfer of ownership

packages/polkadot-api/README.md, packages/polkadot-api/package.json
Despite the fact that we own the `@polkadot-api/*` npm org, we have not been able to publish under the `polkadot-api` npm package due to the fact that [there is someone squatting on a package with an almost identical name](https://github.com/Ajay-Dhore/polkadot_npm). Therefore, for now we will use the `polkadot-connect` package name.
=> `polkadot-api` -> `polkadot-connect`

packages/observable-client/CHANGELOG.md, packages/observable-client/src/chainHead/streams/pinned-blocks.ts, packages/observable-client/tests/fixtures.ts, packages/observable-client/tests/observableClient-stopError.spec.ts
The first block on the `finalizedBlockHashes` list of the `initialized` event was not referencing its correct parent when the list had more than one item.
=> fix(observable-client): reference correct parent

packages/client/CHANGELOG.md, packages/codegen/CHANGELOG.md, packages/codegen/src/types-builder.ts
=> fix(codegen): stringify struct keys

packages/cli/turbo.json
This should really fix turbo cache on CI 🙏
I managed to reproduce the turbo cache issue on local:
1. `turbo build | grep cli`
2. Take note of the cli hash
3. Look at turbo cache folder - Every package has a .tar file, and CLI's look suspiciously empty. Extracting it only contains the build logs.
=> build: set correct output path for turbo on CLI

packages/client/CHANGELOG.md, packages/json-rpc/logs-provider/CHANGELOG.md, packages/json-rpc/logs-provider/package.json, packages/json-rpc/logs-provider/src/logs-provider.ts
Sr25519 signatures are not referentially transparent, because of that the logs-provider was failing when there were transactions involved because it found messages that didn't match with what it was on the logs. This is a workaround to prevent that from happening.
=> fix(logs-provider): support logs with transactions

integration-tests/log-replays/src/main.ts
This will show the errors thrown on the spawned processes of log-replay tests onto the CI logs.
We had a test failing on #427 which was probably due to the build cache, as only after clearing it, it passed. But we were getting that the "process exited with status -1" instead of the detailed error, which would help understanding the issue.
=> ci: log test failures on log-replay tests

packages/client/CHANGELOG.md, packages/client/src/client.ts, packages/client/src/types.ts, packages/observable-client/tests/mockSubstrateClient.ts, packages/substrate-client/CHANGELOG.md, packages/substrate-client/src/chainspec.ts, packages/substrate-client/src/index.ts
=> feat(client): add `getChainSpecData`

packages/substrate-client/CHANGELOG.md, packages/substrate-client/src/chainhead/body.ts, packages/substrate-client/src/chainhead/call.ts, packages/substrate-client/src/chainhead/chainhead.ts, packages/substrate-client/src/chainhead/header.ts, packages/substrate-client/src/chainhead/operation-promise.ts, packages/substrate-client/src/chainhead/storage-subscription.ts, packages/substrate-client/src/chainhead/unpin.ts, packages/substrate-client/src/chainspec.ts, packages/substrate-client/src/index.ts, packages/substrate-client/src/methods.ts, packages/substrate-client/src/request-compatibility-enhancer.ts, packages/substrate-client/src/transaction/transaction.ts, packages/substrate-client/tests/chainHead-functions.spec.ts, packages/substrate-client/tests/chainHead-operations.spec.ts, packages/substrate-client/tests/chainHead.spec.ts, packages/substrate-client/tests/fixtures.ts
There are many different versions in the wild with different permutations of the methods that we want to use, that I decided to handle all that stuff in a "request" enhancer. It's worth pointing out that it was about to get worse, due to the fact that `smoldot` just made the `chainHead` group of functions stable. So, these changes make the library compatible with the new version of smoldot, as well.
=> fix(substrate-client): improve compatibility handling

packages/client/CHANGELOG.md, packages/client/src/re-exports.ts, packages/client/src/tx.ts, packages/codegen/src/generate-descriptors.ts, packages/codegen/src/generate-types.ts, packages/codegen/src/types-builder.ts, packages/substrate-bindings/CHANGELOG.md, packages/substrate-bindings/src/codecs/scale/Variant.ts, packages/substrate-bindings/src/types/GetEnum.ts, packages/substrate-bindings/src/types/enum.ts, packages/substrate-bindings/src/types/index.ts
As a small example, `XcmV4JunctionNetworkId` added an additional variant `PolkadotBulletin`. In this case:
Another change this includes is that `Enum<T>` has a a `{ [type]: value }` shape for the generic, so we don't need the `IEnum<T>` anymore:
=> feat(enum): make enums assignable to other enum types if they are compatible

integration-tests/zombie-tests/src/main.spec.ts, packages/client/CHANGELOG.md, packages/client/src/tx.ts
While working on #450 I noticed that the typings of the "hinted" sign-extensions were wrong.
=> fix(client): types of hinted-sign-extensions

packages/signers/pjs-signer/src/injected-extensions.ts
This PR fixes a bug when connecting a wallet to a dapp: if user connects one or more EVM account, `getInjectedExtension` throws an error. 
Fix: updated the `getInjectedExtension` logic to ignore all accounts that do not have a type expected/supported by PAPI.
=> fix: getInjectedExtension to ignore unsupported account types

packages/client/CHANGELOG.md, packages/client/src/client.ts, packages/client/src/types.ts
BREAKING CHANGE: `watchBlockBlody` was renamed to `watchBlockBody` as
expected. A typo appeared and it has been fixed.
=> fix(client)!: typo in top-level field

packages/client/CHANGELOG.md, packages/client/src/storage.ts
While we were investigating a performance bottleneck on a DApp created by @0xKheops we ended up realizing that the culprit was the subscription the `Sytem.Number` storage entry which was triggering [this issue on smoldot](https://github.com/smol-dot/smoldot/issues/1804).
I showed @0xKheops that he didn't have to use `System.Number`, because the client already offers a way for accessing the block-number, which is much more performant... Then I realized that it would be a good idea to bake-in this performance optimization into our typed-api storage entry. Which is to avoid running the storage operation of the consumer is accessing the storage entry `System.Number`.
=> perf(client): avoid storage operation on `System.Number`

packages/client/CHANGELOG.md, packages/client/src/get-create-tx.ts
BREAKING CHANGE: From now on, we consider the default for a transaction
to be mortal, with a period of 64 blocks. This will prevent potential
reply attacks.
=> fix(client)!: make mortality default to be mortal

integration-tests/zombie-tests/src/main.spec.ts, packages/client/CHANGELOG.md, packages/client/src/tx.ts
As @carlosala pointed out, it is preferable not to pass the whole signer, because in the end the `getEstimateFees` function should not be calling the `sign` function of the signer. Therefore, since the only thing that we need in order to calculate the fees is the public key (so that we can get its nonce, which can alter the len of the extrinsic and thus its fees), then this PR ensures that's the only thing that's passed into the function.
=> fix(client): improve `getEstimateFees`

packages/client/CHANGELOG.md, packages/metadata-builders/tests/__snapshots__/dynamic-builder.spec.ts.snap, packages/substrate-bindings/CHANGELOG.md, packages/substrate-bindings/src/types/enum.ts, packages/view-builder/tests/__snapshots__/view-builder.spec.ts.snap
This PR moves the methods in the enum values `is` and `as` into the `Enum` function, so it can be imported and used as a utility.
It's a breaking change, with a simple migration:
```ts
declare const multiAddress: MultiAddress;
if (multiAddress.is("Raw"))
console.log(multiAddress.value.asHex())
else
console.log(multiAddress.as("Index"))
// Becomes
if (Enum.is(multiAddress, "Raw"))
console.log(multiAddress.value.asHex())
else
console.log(Enum.as(multiAddress, "Index"))
```
=> feat: move `as` and `is` from enum values to `Enum`

packages/client/CHANGELOG.md, packages/substrate-client/CHANGELOG.md, packages/substrate-client/src/chainhead/operation-promise.ts, packages/substrate-client/src/chainhead/storage-subscription.ts, packages/substrate-client/tests/chainHead-operations.spec.ts
Closes #470 
As I mentioned in [this comment](https://github.com/polkadot-api/polkadot-api/issues/470#issuecomment-2091919852):
> To be fair, I now realize that the proper way of canceling an operation for which we haven't received its `started` event should be improved. I.e we should wait until receiving the `started` response and in that same moment trigger the `stopOperation` request.
This is the improvement introduced by this PR.
=> fix(substrate-client): improve operation cancelation logic

integration-tests/zombie-tests/src/main.spec.ts, packages/client/CHANGELOG.md, packages/client/src/get-create-tx.ts, packages/client/src/tx.ts, packages/client/src/types.ts
It partially solves #477. However, there is one more thing that I want to do before closing #477.
What this PR does is to add the ability to create (and validate, broadcast, etc) "optimistic" transactions. What I mean by that is that by default a transaction gets created against the currently finalized block. Which means that the mortality of the transaction, its nonce and its validation will take place against the currently finalized block. However, there are instances where a block that just got announced (and that it's not yet finalized) changes the state in a way that we may want to submit a transaction against that block ASAP, which means that if the block in question ends up becoming finalized, then the "optimistic" transaction should also get into a block that will eventually be …
=> feat(client): support "optimistic" transactions

integration-tests/zombie-tests/src/main.spec.ts, packages/client/CHANGELOG.md, packages/client/src/get-create-tx.ts, packages/client/src/signed-extensions/chain/CheckNonce.ts, packages/client/src/tx.ts, packages/client/src/types.ts
=> feat(client): TX allow user to pass the nonce

integration-tests/zombie-tests/src/main.spec.ts, packages/client/CHANGELOG.md, packages/client/src/index.ts, packages/client/src/tx.ts, packages/client/src/types.ts, packages/observable-client/CHANGELOG.md, packages/observable-client/src/chainHead/chainHead.ts, packages/observable-client/src/chainHead/enhancers/whileBestBlock.ts, packages/observable-client/src/chainHead/streams/block-operations.ts, packages/observable-client/src/chainHead/track-tx.ts, packages/observable-client/src/chainHead/validate-tx.ts, packages/observable-client/src/index.ts
This PR fixes 2 important issues:
- It keeps on validating the transaction after it has been broadcasted
- It makes the payload of the `bestChainBlockIncluded` consistent with the payload of the `finalized` event
It also sets the ground to make the rest of the TX improvements much simpler.
=> fix(client): detect invalid tx after broadcast

packages/client/CHANGELOG.md, packages/client/src/client.ts, packages/client/src/constants.ts, packages/client/src/descriptors.ts, packages/client/src/runtime.ts, packages/client/src/tx/tx.ts, packages/codegen/CHANGELOG.md, packages/codegen/src/generate-descriptors.ts
This will have a really good effect on dApps using multiple chains without the need for a whitelist. On papi-teleporter, without whitelist:
```sh
dist/index.html                                           0.45 kB │ gzip:   0.31 kB
dist/assets/index-BB_EzF1Y.css                           17.16 kB │ gzip:   4.00 kB
dist/assets/checksums-G76RJU2V-DxShV170.js               24.33 kB │ gzip:  14.42 kB
dist/assets/index-DkOWvDP3.js                           693.08 kB │ gzip: 237.72 kB
dist/index.html                                           0.45 kB │ gzip:   0.31 kB
dist/assets/index-BB_EzF1Y.css                           17.16 kB │ gzip:   4.00 kB
dist/assets/checksums-G76RJU2V-DxShV170.js               24.33 kB │ gzip:  14.42 kB
dist/assets/descriptors-2PSCKWSU-C0Cze290.js            213.73 kB …
```
=> feat: lazy load descriptor values

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/src/commands/update.ts, packages/client/CHANGELOG.md, packages/client/package.json
Closes #511 and improves the post-update `generate`.
=> fix(cli): download metadata in parallel plus generate all

integration-tests/log-replays/turbo.json, packages/cli/CHANGELOG.md, packages/client/CHANGELOG.md, packages/client/package.json, packages/client/src/descriptors.ts, packages/client/src/runtime.ts, packages/codegen/CHANGELOG.md, packages/codegen/src/generate-descriptors.ts, packages/codegen/src/generate-multiple-descriptors.ts, pnpm-lock.yaml
This changes the format of the generated descriptors to reduce the chunk size when multiple chains are used.
on papi-teleporter, which uses 8 chains, decreases parsed by 56%, gzipped by 50%:
```
dist/assets/descriptors-CAQHISEQ-D2CBgjrG.js            214.72 kB │ gzip:  51.33 kB
// becomes
dist/assets/descriptors-HTVGGBLK--6L_7V2l.js             93.19 kB │ gzip:  26.15 kB
```
Unfortunately, it increases slightly the size of chunks with only one chain. On our vite example, increases parsed by 13%, gzipped by 11%:
```
dist/assets/descriptors-MT2IRGUU-4e79d6ca.js     32.51 kB │ gzip: 11.60 kB
// becomes
dist/assets/descriptors-JIJEZZAP-4573a30e.js     36.59 kB │ gzip: 12.84 kB
```
=> feat: compact size of generated descriptor values

packages/substrate-client/CHANGELOG.md, packages/substrate-client/package.json, packages/substrate-client/src/client/createClient.ts, pnpm-lock.yaml
- `@polkadot-api/utils` is used during runtime hence should be part of `dependencies`
- Use type import for `@polkadot-api/json-rpc-provider`
Fixes #534
=> fix(substrate-client): add `utils` as dependency

packages/client/src/storage.ts
=> fix: storage entries arguments for fixed size array keys

packages/observable-client/CHANGELOG.md, packages/observable-client/src/chainHead/chainHead.ts, packages/observable-client/tests/observableClient-storage.spec.ts
I noticed that the cache was working for on-going requests/streams. However, once those observables completed the cache was starting the side-effects again. This PR addresses the issue. I have also added 2 new tests to ensure that we don't have regressions on this.
=> fix(observable-client): caching issue

packages/codegen/src/known-types.ts, packages/metadata-builders/CHANGELOG.md, packages/metadata-builders/src/dynamic-builder.ts, packages/metadata-builders/src/lookups.ts, packages/metadata-builders/tests/__snapshots__/checksum-builder.spec.ts.snap, packages/migrate-known-types/.gitignore, packages/migrate-known-types/README.md, packages/migrate-known-types/package.json, pnpm-lock.yaml
- use `bigCompact` when required on `dynamic-builder`
- remove possibly bogus `void`s from `struct`/`tuple`/`array`
=> fix(metadata-builders): various fixes

packages/client/CHANGELOG.md, packages/client/src/tx/create-tx.ts, packages/signers/pjs-signer/CHANGELOG.md, packages/signers/pjs-signer/src/from-pjs-account.ts, packages/signers/pjs-signer/src/injected-extensions.ts, packages/signers/pjs-signer/src/types.ts, packages/signers/polkadot-signer/CHANGELOG.md, packages/signers/polkadot-signer/src/types.ts, packages/signers/signer/CHANGELOG.md, packages/signers/signer/package.json, packages/signers/signer/src/from-raw-signer.ts, packages/signers/signer/src/index.ts, packages/signers/signer/tests/signBytes.spec.ts, pnpm-lock.yaml
When I came up with the `PolkadotSigner` I thought that it was pointless to add a method for just singing raw data, because the `PolkadotSigner` builds on top of a raw-signer... therefore, I thought it was pointless. However, unsurprisingly, the polkadot-js signer that you get OOTB comes with a rather convoluted signer for singing raw data, which is why I decided to add the "raw" signer into this interface so that Polkadot-API users don't have to deal with the leaky abstractions of PJS.
=> feat(signer)!: add support for `signBytes`

packages/client/CHANGELOG.md, packages/client/src/compatibility.ts
Closes #580
Previously I added the descriptor type all the way down to the CompatibilityToken to make typescript show an error if someone tries to use one token from one chain into the function of another chain. I did this by setting a private property holding the type of the descriptor in the token, and then making the compatibility function only accept tokens with that property with that type. Reducing to a simple playground:
```ts
class Token<D> {
constructor(protected _val: D) {}
}
type Api<D> = {
api: {
getStuff: (runtime: Token<D>) => boolean
}
token: Token<D>
}
const n: Api<number> = null as any
const s: Api<string> = null as any
n.api.getStuff(n.token)
// OK
n.api.getStuff(s.token)
// Argument of type 'Token<string>' is not assignable to parameter of type 'Token<number>'
// Type …
```
=> fix: adjust descriptor generic variance on typedApi

packages/cli/package.json, packages/json-rpc/ws-provider/package.json, pnpm-lock.yaml
There's a `high` (7.5 / 10 CVSS) DoS security vulnerability being reported by dependabot, affecting `ws` verson `>= 8.0.0, < 8.17.1`. That was fixed with version `8.17.1`.
Reference: websockets/ws#2230
=> build: bump `ws`

packages/client/src/storage.ts
When conditionally setting optional property, it's common to do an inline ternary condition & set the key to `undefined` to remove it. Right now, this would break `isOptionalArg` check, which doesn't explicitly check for `undefined`.
=> fix(client): optional argument with key explicitly set to `undefined`

packages/cli/CHANGELOG.md, packages/cli/src/commands/update.ts, packages/client/CHANGELOG.md
🙈 I didn't realise `papi update` was already calling the codegen after updating the metadata.
=> fix(cli): `papi update` runs codegen two times when called

packages/cli/package.json, packages/cli/src/commands/generate.ts, packages/cli/src/packageManager.ts, pnpm-lock.yaml
Currently, the library we were using to detect the package manager doesn't work for monorepo/workspaces, as raised here https://github.com/egoist/detect-package-manager/issues/12
In my test environment it did work coincidentally, because it automatically falls back to w/e you have installed if it can't find the lock file. And for some reason it wasn't detecting my yarn installation, falling back to the correct package manager.
As it doesn't seem that that package will update anytime soon, I moved this logic over to our codebase. Might refactor back to an external library when it becomes available.
=> fix(cli): detect correct package manager on monorepos

packages/substrate-bindings/CHANGELOG.md, packages/substrate-bindings/src/storage.ts
Filter by `Boolean` incorrectly filter out all `Identity` encoder.
=> fix(substrate-bindings): bytes to skip

packages/cli/CHANGELOG.md, packages/client/CHANGELOG.md, packages/codegen/CHANGELOG.md, packages/metadata-builders/CHANGELOG.md, packages/metadata-builders/src/checksum-builder.ts, packages/metadata-builders/tests/__snapshots__/checksum-builder.spec.ts.snap, packages/metadata-compatibility/CHANGELOG.md, packages/observable-client/CHANGELOG.md, packages/signers/pjs-signer/CHANGELOG.md, packages/view-builder/CHANGELOG.md
Found and raised by @ggwpez, on some cases there are events that have the same checksum as calls.
For example, the polkadot people chain has checksum `666bl2fqjkejo` for `AmbassadorReferenda.refund_decision_deposit` call, but also for the event `AmbassadorReferenda.ConfirmStarted`. This is because `refund_decision_deposit` only takes `{ index: u32 }` and `ConfirmStarted`'s payload is also `{ index: u32 }`.
Our codegen + compatibility assumes every interaction with the same checksum could be merged into the same descriptor entry point, but that was not the case, since transactions have them through `args` (i.e. they are values being sent) and events have them through `values` (i.e. they are being received). So in runtime the compatibility check failed because the entry points were …
=> fix(codegen): descriptors entry points when transaction and events have the same checksum

packages/signers/pjs-signer/CHANGELOG.md, packages/signers/pjs-signer/src/injected-extensions.ts
As @hannahredler rightfully pointed out: it really doesn't make sense to return `null`.
=> change(pjs-signer): improve `getInjectedExtensions` signature

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/client/CHANGELOG.md, packages/client/package.json, packages/json-rpc/logs-provider/CHANGELOG.md, packages/json-rpc/logs-provider/package.json, packages/known-chains/CHANGELOG.md, packages/known-chains/package.json
I've cherry-picked the fixes into a `release/1.0` branch.
My idea after this is merged and published, is that we can merge it into main to have the fixes there as well.
=> chore: publish polkadot-api@1.0.2

packages/cli/CHANGELOG.md, packages/cli/src/commands/generate.ts, packages/client/CHANGELOG.md, packages/client/src/index.ts, packages/client/src/types.ts, packages/codegen/CHANGELOG.md, packages/codegen/src/generate-descriptors.ts, packages/codegen/src/generate-multiple-descriptors.ts, packages/codegen/src/types-builder.ts, packages/metadata-builders/CHANGELOG.md, packages/metadata-builders/src/lookups.ts, packages/metadata-compatibility/CHANGELOG.md, packages/observable-client/CHANGELOG.md, packages/view-builder/CHANGELOG.md
When working with multiple chains at once, it's often convenient to have a union of `typedApi`s in order to create utility functions to be reused across all of the chains.
However, TS adds a lot of friction when dealing with cases where types don't have a 1-to-1 overlap. And transactions that take in call data are most affected by that, since a call data of one chain doesn't overlap very well with another of another chain.
This change replaces every callData found in a chain for a generic `TxCallData`, which is just `{ type: string, value: { type: string, value: any } }`, to reduce friction when dealing with unions of TypedApis.
It's not a breaking change since it's a change on the type level which only broadens the type. For those who still want type safety with those, the descriptors …
=> feat(tx): improve DX with unions of TypedApi

packages/cli/CHANGELOG.md, packages/client/CHANGELOG.md, packages/client/src/compatibility.ts, packages/codegen/CHANGELOG.md, packages/codegen/src/generate-descriptors.ts, packages/codegen/src/whitelist.ts, packages/metadata-compatibility/CHANGELOG.md, packages/metadata-compatibility/src/typedef.ts
This PR is better suited to merge with rebase than with squash.
=> fix(metadata-compatibility): resolve properly enum types

packages/client/CHANGELOG.md, packages/client/src/constants.ts, packages/client/src/event.ts, packages/client/src/runtime-call.ts, packages/client/src/storage.ts, packages/client/src/tx/tx.ts
We weren't catching at entrypoint creation if the entrypoints indeed existed at the metadata, and therefore errors from inner libraries were being leaked.
Thanks @SBalaguer for the report!
=> fix(client): throw when entrypoint is not found

packages/client/CHANGELOG.md, packages/json-rpc/polkadot-sdk-compat/CHANGELOG.md, packages/json-rpc/polkadot-sdk-compat/src/index.ts, packages/json-rpc/polkadot-sdk-compat/src/parsed-enhancers/fix-descendant-values.ts, packages/json-rpc/polkadot-sdk-compat/src/parsed-enhancers/index.ts, packages/json-rpc/polkadot-sdk-compat/src/utils.ts
This PR introduces a new JSON-RPC enhancer to address the performance bottleneck described in [this issue](https://github.com/paritytech/polkadot-sdk/issues/5589) on the PolkadotSDK node.
Without this enhancement, fetching all descendant values of the `NominationPools.PoolMembers` storage entry can take up to 10 minutes. With this enhancer, the same data retrieval process is reduced to under 10 seconds.
Shout out to our friends at Talisman for bringing this issue to our attention!
cc: @0xKheops @alecdwm
=> feat(polkadot-sdk-compat): add `fixDescendantValues` enhancer

packages/view-builder/CHANGELOG.md, packages/view-builder/package.json, packages/view-builder/src/view-builder.ts
Fixes #679 . Since this package is not released with the top-level client, we can release its patch in this same PR.
=> fix(view-builder): solve recursive shapes issue

packages/cli/CHANGELOG.md, packages/cli/src/commands/generate.ts, packages/client/CHANGELOG.md, packages/codegen/CHANGELOG.md, packages/codegen/src/generate-descriptors.ts
Esbuild doesn't want to fix https://github.com/evanw/esbuild/issues/3894, and we're hitting memory limits again, after upgrading papi to latest version.
This allows us to bypass binary loader and get back to normal memory usage during application startup.
I've created a small repro which fails with OOM on current papi version, but works fine with my changes. 
[papi-repro.tar.gz](https://github.com/user-attachments/files/16981888/papi-repro.tar.gz)
Fixes #654
=> Getting around startup memory spike

packages/client/CHANGELOG.md, packages/json-rpc/polkadot-sdk-compat/CHANGELOG.md, packages/json-rpc/polkadot-sdk-compat/src/parsed-enhancers/unpin-hash.ts
This bug was probably harmless, because it only affected the "fire and forget" requests... Nevertheless, it had to be fixed 😬
=> fix(polkadot-sdk-compat): fix unpin-hash enhancer

packages/client/CHANGELOG.md, packages/json-rpc/json-rpc-provider-proxy/CHANGELOG.md, packages/json-rpc/json-rpc-provider-proxy/src/subscription-manager/chainHeadFollow.ts, packages/json-rpc/polkadot-sdk-compat/CHANGELOG.md, packages/json-rpc/polkadot-sdk-compat/src/index.ts, packages/json-rpc/polkadot-sdk-compat/src/parsed-enhancers/fix-premature-blocks.ts, packages/json-rpc/polkadot-sdk-compat/src/parsed-enhancers/index.ts, packages/json-rpc/ws-provider/CHANGELOG.md, packages/json-rpc/ws-provider/src/ws-provider.ts
There are 3 commits in this PR. They are all a bit related:
1) add the `fixPrematureBlocks` enhancer which fixes #713 which is a confirmed bug on the [polkadot-sdk node](https://github.com/paritytech/polkadot-sdk/issues/5761). I have been able to test the enhancer when the issue occurs and things keep working perfectly fine.
2) As of today it's not possible to know whether a stop event comes from the outside or it was triggered by the json-rpc-provider-proxy. The second commit adds a property to distinguish the internal from the external stop events.
3) Improve the logs of the ws-provider.
=> Fix premature json rpc enhancer

packages/client/CHANGELOG.md, packages/client/package.json, packages/client/sync-packages.mjs
This PR improves the DX by showing subpath imports with multiple path levels in IDE Intellisense. This should have no downsides and `sync-packages.mjs` has been updated accordingly.
Idea from [RxJS](https://github.com/ReactiveX/rxjs/blob/f9f07f14ff15cc5f81e4b34005286efb4b5cabc1/packages/rxjs/package.json#L53-L58) and [Ramda](https://github.com/ramda/ramda/blob/173ceba9ab89a28428b4794594dc436b993a932b/package.json#L59-L61)
=> fix(client): use glob for subpackages

packages/client/CHANGELOG.md, packages/signers/pjs-signer/CHANGELOG.md, packages/signers/pjs-signer/src/types.ts
I believe these accounts are just plain `InjectedAccount` until transformed with `toPolkadotInjected`.
=> fix(pjs-signer): incorrect PJS injected account type

packages/codegen/src/internal-types/generate-typescript.ts, packages/codegen/src/types-builder.ts
For compact numbers, the intermediate type representation is a union, which is not a primitive.
However, for codegen purposes, we can just inline union types instead of assigning an anonymous type to them. I've also removed the brackets of union types when there's only one inner type.
=> fix(codegen): type collision with compact numbers

examples/bun/src/switch-rpcs.ts, packages/client/CHANGELOG.md, packages/json-rpc/ws-provider/CHANGELOG.md, packages/json-rpc/ws-provider/src/ws-provider.ts
These changes introduce a number of long-awaited improvements into the ws-provider:
1) It has a new overload which allows the consumer to pass a list of endpoints. The client will rotate over these different endpoints every time that there is a connection issue with one of them.
2) There are 2 different ways of introspecting on the status of the protocol layer:
- Passing a `statusChange` callback when creating the client
- Calling the `getStatus` function on the `WsJsonRpcProvider`
3) The user can proactively trigger a `switch` if they want to force the client to move to a different endpoint.
4) The client will automatically timeout if the connection with the RPC doesn't open in a timely manner, and then it will try to reconnect with the next RPC endpoint.
The current interfaces are …
=> feat(ws-provider): new APIs and improvements

packages/cli/CHANGELOG.md, packages/client/CHANGELOG.md, packages/codegen/CHANGELOG.md, packages/descriptors/package.json, packages/docgen/CHANGELOG.md, packages/json-rpc/json-rpc-provider-proxy/CHANGELOG.md, packages/json-rpc/json-rpc-provider-proxy/src/get-proxy.ts, packages/json-rpc/json-rpc-provider/CHANGELOG.md, packages/json-rpc/logs-provider/CHANGELOG.md, packages/json-rpc/polkadot-sdk-compat/CHANGELOG.md, packages/json-rpc/sm-provider/CHANGELOG.md, packages/json-rpc/ws-provider/CHANGELOG.md, packages/known-chains/CHANGELOG.md, packages/known-chains/build.sh, packages/merkleize-metadata/CHANGELOG.md, packages/metadata-builders/CHANGELOG.md, packages/metadata-compatibility/CHANGELOG.md, packages/metadata-fixtures/package.json, packages/observable-client/CHANGELOG.md, packages/signers/ledger-signer/CHANGELOG.md, packages/signers/pjs-signer/CHANGELOG.md, packages/signers/polkadot-signer/CHANGELOG.md, packages/signers/signer/CHANGELOG.md, packages/smoldot/CHANGELOG.md, packages/substrate-bindings/CHANGELOG.md, packages/substrate-client/CHANGELOG.md, packages/utils/CHANGELOG.md, packages/view-builder/CHANGELOG.md, tsconfig.base.json
Iterators `forEach` is still widely experimental and is not supported on Firefox, Safari, Node LTS and Bun.
https://caniuse.com/mdn-javascript_builtins_iterator_foreach
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/forEach
Closes #770
=> fix: target `es2022` and lib `es2023` on builds

examples/html-umd/index.html
The html-umd example was using an `async` function with a huge try/catch which was completely bogus b/c there is no promise being resolved in it. This PR simply fixes that. Also, it seems that the file wasn't prettified, so when I saved a lot of other non-relevant diffs appeared, oh well...
=> nit(examples): improve hmtl-umd example

.github/workflows/publish.yml, examples/bun/package.json, examples/bun/src/tx-utils.ts, packages/tx-utils/CHANGELOG.md, packages/tx-utils/README.md, packages/tx-utils/package.json, packages/tx-utils/src/decode-extrinsic.ts, packages/tx-utils/src/from-pjs-to-tx-data.ts, packages/tx-utils/src/get-metadata.ts, packages/tx-utils/src/index.ts, packages/tx-utils/src/pjs-tx-helper.ts, packages/tx-utils/src/signed-extensions/chain/CheckGenesis.ts, packages/tx-utils/src/signed-extensions/chain/CheckMetadataHash.ts, packages/tx-utils/src/signed-extensions/chain/CheckNonce.ts, packages/tx-utils/src/signed-extensions/chain/CheckSpecVersion.ts, packages/tx-utils/src/signed-extensions/chain/CheckTxVersion.ts, packages/tx-utils/src/signed-extensions/chain/index.ts, packages/tx-utils/src/signed-extensions/get-signed-extension-parts.ts, packages/tx-utils/src/signed-extensions/index.ts, packages/tx-utils/src/signed-extensions/internal-types.ts, packages/tx-utils/src/signed-extensions/user/ChargeAssetTxPayment.ts, packages/tx-utils/src/signed-extensions/user/ChargeTransactionPayment.ts, packages/tx-utils/src/signed-extensions/user/CheckMortality.ts, packages/tx-utils/src/signed-extensions/user/index.ts, packages/tx-utils/src/signed-extensions/utils.ts, packages/tx-utils/src/types.ts, packages/tx-utils/tsconfig.json, pnpm-lock.yaml
This is a new library meant mostly to assist PJS extensions to stop using PJS internally. The frens from Talisman have already started this process and @0xKheops asked for these kinds of helpers.
This is an important topic in our roadmap. I hope that this library can help them in these process.
=> feat(tx-utils): add new `tx-utils` library

packages/client/CHANGELOG.md, packages/client/src/tx/create-tx.ts
We should also create an API that allows providing custom sign-extension values while creating the transaction. That PR will come later. However, it doesn't make sense not to allow the signer to deal with custom sign-extensions that the signer may want to deal on their own. So, we shouldn't throw and just provide the signer with the signed-extension data that we know how to deal with.
=> fix(client): not throw on unknown signed-extensions

packages/client/CHANGELOG.md, packages/substrate-bindings/CHANGELOG.md, packages/substrate-bindings/src/codecs/scale/Binary.ts
Unfortunately, some of the XCM metadata definitions point to the type-definition for a generic `[u8; 32]` type, rather than routing it via the `AccountId32` type... Because of that, the typings expect a `FixedSizeBinary<32>`. Since converting an ss58-address into a FixedSizeBinary is something that probably most users won't know how to easily do, I thought about adding this new static method to alleviate the issue.
Before:
```ts
XcmV3Junction.AccountId32({
network: undefined,
id: FixedSizeBinary.fromBytes(AccountId().enc(dest)),
})
```
After:
```ts
XcmV3Junction.AccountId32({
network: undefined,
id: FixedSizeBinary.fromAccountId32(dest),
})
```
=> feat(client): add `fromAccountId32` on `FixedSizeBinary`

packages/client/CHANGELOG.md, packages/signers/pjs-signer/CHANGELOG.md, packages/signers/pjs-signer/src/injected-extensions.ts, packages/signers/pjs-signer/src/types.ts
The `injectedWeb3.enable` function expects a Dapp name param, that is then displayed to users.
I kept it optional here so as not to break any existing implementation.. but I'm actually surprised it's been working so far without a name, since it seems to be a required param, see here https://github.com/polkadot-js/extension/blob/master/packages/extension-inject/src/bundle.ts#L42
In any case this should let users see a nice Dapp name in the authorization screen. Note that more than a nice to have, I rely on this Dapp name for testing, e.g in https://github.com/ChainSafe/cypress-polkadot-wallet so that devs can emulate an extension in a e2e environment, and authorize specific dapps, by name, programmatically.
=> Add optional dappName param to `connectInjectedExtension`

packages/client/CHANGELOG.md, packages/client/src/storage.ts, packages/client/src/tx/create-tx.ts, packages/client/src/tx/signed-extensions/internal-types.ts, packages/client/src/tx/signed-extensions/utils.ts
=> feat(client): support `u64`-based block numbers

packages/ink-contracts/CHANGELOG.md, packages/ink-contracts/src/get-lookup.ts
I had an issue on the previous implementation - By reusing lookupEntries we can also reuse the existing codegen to generate the types for ink! storage, but because lookup resolves pointers (composites of just one element) and nested root layouts were being removed, this resulted in an inaccurate representation.
As an example, standard PSP22 has a `data` field in storage with the following layout:
```ts
data: {
type: "struct",
value: [{
name: "total_supply",
type: "u128"
}, {
name: "balances",
type: "root(Map<AccountId, u128>)"
}, {
name: "allowances",
type: "root(DoubleMap<[AccountId,AccountId], u128>)"
}]
}
```
The previous implementation would leave `balances` and `allowances` empty, because they are nested storage roots, so `data` would become a struct with a single field …
=> fix(ink-codegen): keep original storage layout

examples/ink/index.ts, examples/ink/package.json, packages/client/CHANGELOG.md, packages/client/src/tx/submit-fns.ts, packages/client/src/tx/types.ts, packages/codegen/CHANGELOG.md, packages/ink-contracts/CHANGELOG.md, packages/ink-contracts/src/dynamic-builders.ts, packages/ink-contracts/src/ink-client.ts, packages/ink-contracts/src/metadata-types.ts, packages/observable-client/CHANGELOG.md, packages/observable-client/src/chainHead/streams/get-runtime-creator.ts, pnpm-lock.yaml
Previously I assumed that events in ink! are encoded as enums, just like regular events.
However, this changed [on ink! v5](https://use.ink/faq/migrating-from-ink-4-to-5#events-20), where only the payload is encoded. To know which codec to use, now events come with a `signatureTopic` so they can be looked up from the `topics` array on events. This PR adds support for v5 events by decoding them through the signatureTopic.
=> feat(ink): decode v5 events

packages/json-rpc/ws-provider/CHANGELOG.md, packages/json-rpc/ws-provider/src/follow-enhancer.ts, packages/json-rpc/ws-provider/src/ws-provider.ts
Added an internal `followEnhancer` to address issues with certain RPC providers where misconfigured middlewares incorrectly trigger errors on `chainHead_v1_follow` requests, even though the client hasn't reached the 2-subscription limit.
What the enhancer does is to trigger a `switch` on the `WsJsonRpcProvider` when this situation occurs. The reason why this is effective is because the issue with these RPC providers is that they perform a round-robin on the underlying stateful WS connections with the PolkadotSDK nodes. Therefore, disconnecting and reconnecting can help at hitting a different PolkadotSDK node in which the limit has not yet being reached. It's worth pointing out that this is just an attempt on alleviating an upstream problem that must be addressed by these RPC providers. …
=> fix(ws-provider): `follow` enhancer

packages/json-rpc/json-rpc-provider-proxy/CHANGELOG.md, packages/json-rpc/json-rpc-provider-proxy/src/get-proxy.ts, packages/json-rpc/ws-provider/CHANGELOG.md, packages/json-rpc/ws-provider/src/follow-enhancer.ts
#853 didn't quite have the effect that we expected. This PR amends that.
In order to make sure that it now has the effect that we wanted, I did test it against a custom WS proxy built with bun:
```ts
let nConnections = 0
let responseIdx = 0
const responses = [
'{"jsonrpc":"2.0","result":{"methods":["account_nextIndex","archive_unstable_body","archive_unstable_call","archive_unstable_finalizedHeight","archive_unstable_genesisHash","archive_unstable_hashByHeight","archive_unstable_header","archive_unstable_storage","author_hasKey","author_hasSessionKeys","author_insertKey","author_pendingExtrinsics","author_removeExtrinsic","author_rotateKeys","author_submitAndWatchExtrinsic","author_submitExtrinsic","author_unwatchExtrinsic","chainHead_v1_body","chainHead_v1_call","chainHead_v1_continue","c …
```
=> Fix JSON-RPC providers

integration-tests/zombie-tests/src/main.spec.ts, packages/cli/CHANGELOG.md, packages/client/CHANGELOG.md, packages/client/src/descriptors.ts, packages/client/src/storage.ts, packages/client/src/types.ts, packages/codegen/CHANGELOG.md, packages/codegen/src/generate-descriptors.ts, packages/codegen/src/generate-docs-descriptors.ts, packages/codegen/src/types-builder.ts, packages/docgen/CHANGELOG.md, packages/ink-contracts/CHANGELOG.md, packages/merkleize-metadata/CHANGELOG.md, packages/metadata-builders/CHANGELOG.md, packages/metadata-compatibility/CHANGELOG.md, packages/observable-client/CHANGELOG.md, packages/react-builder/CHANGELOG.md, packages/signers/ledger-signer/CHANGELOG.md, packages/signers/pjs-signer/CHANGELOG.md, packages/signers/signer/CHANGELOG.md, packages/signers/signers-common/CHANGELOG.md, packages/substrate-bindings/CHANGELOG.md, packages/substrate-bindings/src/storage.ts, packages/substrate-bindings/tests/storage.spec.ts, packages/tx-utils/CHANGELOG.md, packages/view-builder/CHANGELOG.md
For reference: https://github.com/polkadot-api/papi-console/issues/2
=> fix: account for storage entries with opaque keys

packages/cli/CHANGELOG.md, packages/codegen/CHANGELOG.md, packages/codegen/package.json, packages/codegen/src/generate-docs-descriptors.ts, packages/docgen/CHANGELOG.md, packages/docgen/package.json
This PR releases `codegen` and `docgen` packages. This should not yield to multiple versions of `codegen` installed in anyone's set-up since `docgen` is only used in very specific contexts and `codegen` is not meant to be installed standalone.
=> fix(codegen): storage docs generation

packages/observable-client/src/chainHead/chainHead.ts, packages/observable-client/src/chainHead/enhancers/optionalHash.ts
This PR fixes 2 different issues that I encountered on the observable-client while working on the new `watchEntries` API:
1) The first commit addresses an issue that had to do with blocks being mistakenly unpinned after an `operationInnacessible` event. That happened b/c during the waiting time -before retrying- the refcount was going down to zero. This was the root cause of some bizarre `BlockNotPinned` errors.
2) The second commit fixes an issue with the cached-streams: the connector was not being reset after the stream errored.
=> observable-client fixes

packages/client/CHANGELOG.md, packages/client/src/descriptors.ts
This effected, for example, `api.query.ChildBounties.ChildBounties`
=> fix: `unknown` type on storage queries that have a composite key with the same type

packages/cli/CHANGELOG.md, packages/client/CHANGELOG.md, packages/codegen/CHANGELOG.md, packages/docgen/CHANGELOG.md, packages/ink-contracts/CHANGELOG.md, packages/merkleize-metadata/CHANGELOG.md, packages/metadata-builders/CHANGELOG.md, packages/metadata-builders/src/checksum-builder.ts, packages/metadata-builders/src/lookup-graph.ts, packages/metadata-compatibility/CHANGELOG.md, packages/observable-client/CHANGELOG.md, packages/react-builder/CHANGELOG.md, packages/signers/ledger-signer/CHANGELOG.md, packages/signers/meta-signers/CHANGELOG.md, packages/signers/pjs-signer/CHANGELOG.md, packages/signers/signer/CHANGELOG.md, packages/signers/signers-common/CHANGELOG.md, packages/tx-utils/CHANGELOG.md, packages/view-builder/CHANGELOG.md
Fixes #923 
This was caused on an assumption we made that we couldn't have self-referencing nodes. We were counting for circularities with multiple groups, but discarded nodes that would reference themselves.
The chain that has this case they have an extrinsic `LiquidityPools.schedule_limit_order_update` that takes as a parameter the same `LiquidityPools` extrinsic enum. So this node would be treated as a non-circular one and thus the max call stack error.
This PR checks for the strongly connected components of size 1 to actually be self-referencing before discarding them.
=> fix(checksum): infinite loop with self-referencing individual nodes

packages/cli/CHANGELOG.md, packages/cli/src/commands/generate.ts, packages/codegen/CHANGELOG.md, packages/codegen/src/generate-descriptors.ts, packages/docgen/CHANGELOG.md
This is needed for the offline apis, but it can also be very useful for debugging and other advanced use-cases. It doesn't increase the bundle-sizes, and -since the file is part of the generated assets- it doesn't bloat the git history either.
=> chore(codegen): include lazy `getMetadata` in descriptors

packages/client/CHANGELOG.md, packages/client/src/descriptors.ts
Fixes #955 
This was introduced in #947, which was fixing the case when querying a storage entry with an opaque hash. As it was previously, the key types were wrong because they were showing the decoded version.
It seems TS does weird stuff when comparing with `extends never`: If the type being compared is never, in this case it would result in `never`, regardless of the type declared in the "true" branch. The only way I could get it to work is by adding a unique type (`Opaque extends never` becomes `Opaque | "a literal that won't be used" extends "a literal that won't be used"`).
But in this case it shouldn't really matter, it looks like we can just map the types directly. If `Opaque` is never, then it won't match against any of the keys and the original tuple will be left intact. I …
=> fix(client): keyArgs for storage entries with concat hashes

integration-tests/chopsticks/src/stop-events.spec.ts, packages/client/CHANGELOG.md, packages/observable-client/CHANGELOG.md, packages/observable-client/src/chainHead/chainHead.ts, packages/observable-client/src/chainHead/streams/pinned-blocks.ts
Also fixed a small memory leak after stop event.
=> fix: finalized$ emits blocks that are not pinned after a stop event recovery

packages/client/CHANGELOG.md, packages/client/src/client.ts
Some local networks start with a corrupted state, which gets fixed in the first block.
Nevertheless, with `InstantSeal`, the block only gets produced after the first transaction, which can't be created with the corrupted state.
=> fix(client): take `genesisHash` from RPC

integration-tests/chopsticks/package.json, integration-tests/chopsticks/setupTests.ts, integration-tests/chopsticks/src/chopsticks.ts, integration-tests/chopsticks/src/chopsticksUtils.ts, integration-tests/chopsticks/src/stop-events.spec.ts, integration-tests/chopsticks/src/storage.spec.ts, integration-tests/chopsticks/vitest.config.ts
It covers just the happy path + opaque keys.
Also reworked the setup of the test so that chopsticks spawns just once when you're running in watch mode. Makes it so much faster to work on tests when you don't have to wait 10 seconds on every test change!
I'd like to have the capacity of creating forks, but chopsticks doesn't have that... It might be possible to do spawning multiple chopsticks instances and with a clever JSON-RPC middleware that switches between them, but that… sounds like I'm probably overthinking.
=> test(storage): basic tests

packages/cli/CHANGELOG.md, packages/cli/src/packageManager.ts, packages/client/CHANGELOG.md, packages/docgen/CHANGELOG.md
Thanks @lrazovic for the report!
=> fix(cli): support `bun.lock` lockfile

packages/cli/CHANGELOG.md, packages/codegen/CHANGELOG.md, packages/metadata-compatibility/CHANGELOG.md, packages/metadata-compatibility/src/isCompatible.ts, packages/metadata-compatibility/src/isStaticCompatible.ts, packages/metadata-compatibility/src/typedef.ts
=> fix(cli, codegen): deal with cyclical enums

packages/codegen/src/ink-types.ts, packages/codegen/src/internal-types/generate-typescript.ts, packages/codegen/src/internal-types/type-representation.ts, packages/ink-contracts/src/ink-client.ts, packages/ink-contracts/src/ink-descriptors.ts, packages/ink-contracts/src/metadata-types.ts
Closes #985 
This adds a `.attributes` property into the messages/constructors of the ink client:
```ts
const psp22 = getInkClient(contracts.psp22);
const increaseAllowance = psp22.message("PSP22::increase_allowance");
console.log(increaseAllowance.attributes); /*
{
payable: false,
default: false,
mutates: true,
}
*/
```
And it also adds a couple of properties to get the default constructor and default message:
```ts
console.log(psp22.defaultMessage, psp22.defaultConstructor)
```
I've updated the codegen so that these properties are actually the label of default message/constructors if it has a default one, and `string | undefined` if it doesn't (I think having this type will make it easier to use in cases where the contract is generic, while still directly removing the "undefined" case …
=> feat(ink): add metadata to callable interface

packages/client/CHANGELOG.md, packages/client/src/tx/create-tx.ts
Currently, the nonce is picked based on where the transaction is being created: If it's created against the finalized block, then it takes the nonce from that block, and if it's against the best block then it's done against that one.
Although papi provides a way manually handling the `nonce`, a recurring issue new users have with the library is running into "stale" transactions because they created a second transaction without waiting for the first one to become finalized.
This changes the default behaviour so that it always looks at the nonce of the latest blocks, regardless of where the transaction is being created.
It won't cover all cases, so consumers are still encouraged to manage the nonce value themselves if they want to create multiple transactions at once (at least until this is …
=> feat(tx): use highest nonce by default

packages/cli/CHANGELOG.md, packages/cli/src/commands/generate.ts, packages/client/CHANGELOG.md
Instead of relying in the local `tsconfig.json` of the user (or the tsup default if it doesn't exist), pin the target to the same one we use for all the other libraries.
Closes #1014
=> fix(cli): pin ES target version for descriptors

packages/client/CHANGELOG.md, packages/client/src/tx/create-tx.ts
=> fix(client): propagate provided `asset` to the signer

packages/client/CHANGELOG.md, packages/observable-client/CHANGELOG.md, packages/observable-client/src/chainHead/streams/follow.ts
Thanks to the feedback provided on a reproduction case by our frens on ParaSpell we were able to identify a rather ugly race-condition that happened when destroying the client. If in the moment of destroying the client we have received the response to the follow-request and the initialized event, then we have a concatMap that waits for the header of the finalized-block, and completing the source observable was not causing the unsubscription of the `concatMap` observable... As a result, the `getHeader` was triggering an error and the `retryChainHeadError` was constantly retrying to re-stablish the follow-subscription... The solution is to unsubscribe from the resulting observable, rather than just completing the source observable.
=> fix(client): solve race-condition on client.destroy

packages/cli/CHANGELOG.md, packages/cli/src/commands/generate.ts, packages/client/CHANGELOG.md, packages/client/src/descriptors.ts, packages/codegen/CHANGELOG.md, packages/codegen/src/generate-descriptors.ts
Something missing I encountered while implementing view functions...
This should go under `next`, since it is an addition and changes the required version of `polkadot-api` in the descriptors package.
=> feat(codegen): expose `<key>Apis`

integration-tests/chopsticks/src/events.spec.ts
The current tests were causing [this false positive](https://github.com/polkadot-api/polkadot-api/actions/runs/15097183042/job/42433410343).
=> test(chopsticks): improve `events` test

packages/cli/src/commands/generate.ts, packages/client/CHANGELOG.md, packages/codegen/CHANGELOG.md, packages/codegen/src/generate-descriptors.ts, packages/codegen/src/generate-docs-descriptors.ts, packages/metadata-builders/CHANGELOG.md, packages/metadata-builders/src/dynamic-builder.ts
At the moment, these entries decode to `undefined`. This makes it impossible to differentiate from a non-existing entry when using `getValue`.
=> fix(metadata-builders): decode to `null` for void entries

integration-tests/zombie-tests/src/main.spec.ts, packages/client/CHANGELOG.md, packages/client/src/tx/signed-extensions/mortal-enc.ts, packages/client/src/tx/signed-extensions/sign-extensions.ts
This follows the same impl as in https://github.com/paritytech/polkadot-sdk/blob/ff5c67c8a3d60ccb3f0af114a07db8f4bec485a0/substrate/primitives/runtime/src/generic/era.rs#L65-L72
=> fix(client): ensure mortality always encode to valid values

packages/client/src/runtime-call.ts, packages/client/src/storage.ts, packages/client/src/viewFns.ts
This change will give the user the options to autocomplete the special values of `best` and `finalized` for the `at` property of the `CallOptions`, but also allows of an arbitrary string like before in order to pass a blockhash value.
=> fix(client): narrow type of `at` property of `CallOptions`

packages/substrate-bindings/CHANGELOG.md, packages/substrate-bindings/src/codecs/blockHeader.ts
This PR fixes a bug in the DigestItem codec implementation where the "Other" variant was not being handled, despite being correctly defined in the DigestItem enum type.
The DigestItem enum in `known-types.ts` correctly defines all variants according to the polkadot-sdk specification:
- `Other` (index 0)
- `Consensus` (index 4)  
- `Seal` (index 5)
- `PreRuntime` (index 6)
- `RuntimeEnvironmentUpdated` (index 8)
However, the codec implementation in `packages/substrate-bindings/src/codecs/blockHeader.ts` was only handling indices `[4, 5, 6, 8]`, missing index 0 for the "Other" variant.
Added the missing "Other" variant to the codec implementation:
```typescript
const diggest = Variant(
{
other: Bytes(),  // Added this line
consensus: diggestVal,
seal: diggestVal,
preRuntime: diggestVal, …
```
=> fix: add missing Other variant to DigestItem codec

packages/client/CHANGELOG.md, packages/observable-client/CHANGELOG.md, packages/observable-client/src/chainHead/streams/pinned-blocks.ts
The finalized-blocks on the `initialized` event were not being added into the usage of the initial-runtime, which means that if one of those blocks was unpinned before a new-block arrived, then the runtime wouldn't be present and the new-block would trigger a runtime error when trying to access its non-existing runtime.
=> fix(observable-client): prevent used runtime to be deleted

packages/client/CHANGELOG.md, packages/observable-client/CHANGELOG.md, packages/observable-client/src/chainHead/chainHead.ts
Some RPCs are erroring on `chainHead_v1_unpin`, by throwing an "Invalid Block Hash" error, even though the block being unpinned was reported by the RPC server and is being unpinned as per the spec.
It happens mainly radiumblock, which is what I have used to debug this, but I've also had it randomly (and extremely rarely) happen with IBP2 (dotters). I've sent a message to the RadiumBlock team to see if they take a look at what might be happening.
Problem is some runtimes (at least bun, and I think nodejs from a specific version onward?) will halt the process when an uncaught exception is thrown, as it was the case for unpin (as it's something being handled internally by polkadot-api). This PR basically adds a `.catch()` to catch the error, but logs it into the console as I still think we …
=> fix: prevent uncaught RPC error on unpin

packages/json-rpc/legacy-provider/CHANGELOG.md, packages/json-rpc/legacy-provider/package.json, packages/json-rpc/legacy-provider/src/upstream/blocks/blocks.ts
The `updates$` stream is not supposed to re-emit the latest finalized event.
=> fix(legacy-provider): avoid redundant `initialized` event

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, .github/workflows/zombienet.yml
A bit of workflow housekeeping:
- Add provenance attestation to our npm packages (adding the cool green check in NPM, proving from which commit and which workflow run we published the package) <img width="1084" height="215" alt="image" src="https://github.com/user-attachments/assets/65291943-f815-41b5-814c-44b8d18aef90" />
- Update to current node LTS, and homogenize versioning across different workflows
- Pin workflow permissions to the minimum required
- Pin version-check workflow (the only one external that is not from GitHub) to avoid supply chain attacks.
- Add Dependabot for reusable workflows update (not for PNPM packages, which is super annoying)
=> ci: housekeeping workflows

packages/cli/CHANGELOG.md, packages/cli/src/cli.ts, packages/cli/src/commands/generate.ts, packages/cli/src/commands/sol.ts, packages/cli/src/papiConfig.ts, packages/client/CHANGELOG.md, packages/codegen/CHANGELOG.md, packages/codegen/src/index.ts, packages/codegen/src/sol-types.ts, packages/ink-contracts/CHANGELOG.md, packages/ink-contracts/src/ink-client.ts, packages/ink-contracts/src/ink-descriptors.ts
This adds support for solidity contracts, by adding `papi sol` subcommand (analogous to `papi ink`) for managing solidity contracts.
The top-level client doesn't currently support solidity encoding, as there are plenty of ethereum libraries that deal with solidity encoding at this abstraction level.
This feature is basically to have a similar codegen of contract types to those of `ink`, so that the same system can be used for solidity in the PAPI ink-sdk to have a consistent API between both languages.
=> feat(cli): generate contract types for solidity contracts
